# -*- coding: utf-8 -*-
"""111~4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fdz31QgQUH2_nkGc5J7WsF1ZyPzXyNAX
"""

#1
class Customer:
  def __init__(self,name):
    self.nam=name
  def greet(self,name1=None):
    self.nam1=name1
    if name1==None:
     print('Hello!')
    else:
     print(f"Hello {self.nam1}!")
  def purchase(self,*n):
    self.count=0
    for i in n:
      self.count+=1
    print(self.nam+',','you purchased',self.count,'item(s):')
    for j in n:
      print(j)
customer_1 = Customer("Sam")
customer_1.greet()
customer_1.purchase("chips", "chocolate", "orange juice")
print("-----------------------------")
customer_2 = Customer("David")
customer_2.greet("David")
customer_2.purchase("orange juice")

#2
class Panda:
  def __init__(self,Name,Gender,Age):
    self.name=Name
    self.gender=Gender
    self.age=Age
  def sleep(self,h=None):
    self.hour=h
    if h==None:
      return(f"{self.name}'s duration is unknown thus should have only  bamboo leaves")
    elif 3<=h<=5:
      return(f'{self.name} sleeps {self.hour} hours daily and should have Mixed Veggies')
    elif 6<=h<=8:
      return(f'{self.name} sleeps {self.hour} hours daily and should have Eggplant & Tofu')
    elif 9<=h<=11:
      return(f'{self.name} sleeps {self.hour} hours daily and should have Broccoli Chicken')
panda1 = Panda("Kunfu","Male", 5)
panda2=Panda("Pan Pan","Female",3)
panda3=Panda("Ming Ming","Female",8)

print("{} is a {} Panda Bear who is {} years old".format(panda1.name,panda1.gender,panda1.age))

print("{} is a {} Panda Bear who is {} years old".format(panda2.name,panda2.gender,panda2.age))

print("{} is a {} Panda Bear who is {} years old".format(panda3.name,panda3.gender,panda3.age))
print("===========================")
print(panda2.sleep(10))
print(panda1.sleep(4))
print(panda3.sleep())

#3
class Cat:
  def __init__(self,colour=None,skill=None):
    self.clr=colour
    self.skl=skill
  def printCat(self):
    if self.clr==None and self.skl==None:
      self.clr='White'
      self.skl='sitting'
    elif self.skl==None:
      self.skl='sitting'
    print(f"{self.clr} cat is {self.skl}")
  def changeColor(self,colour):
    self.clr=colour

c1 = Cat()
c2 = Cat("Black")
c3 = Cat("Brown", "jumping")
c4 = Cat("Red", "purring")
c1.printCat()
c2.printCat()
c3.printCat()
c4.printCat()
c1.changeColor("Blue")
c3.changeColor("Purple")
c1.printCat()
c3.printCat()

#4
class Student:
   def __init__(self,name=None):
     self.nam=name
     if name==None:
       self.nam='default student'
   def quizcalc(self,*n):
     self.total=0
     for i in n:
       self.total+=i
   def printdetail(self):
     print(f"Hello {self.nam}")
     print(f"Your average quiz score is {self.total/3}")


s1 = Student()
s1.quizcalc(10)
print('--------------------------------')
s1.printdetail()
s2 = Student('Harry')
s2.quizcalc(10,8)
print('--------------------------------')
s2.printdetail()
s3 = Student('Hermione')
s3.quizcalc(10,9,10)
print('--------------------------------')
s3.printdetail()

#5
class Student:
  def __init__ (self,name,id,department=None):
    self.nam=name
    self.Id=id
    self.dep=department
    if department==None:
      self.dep='CSE'
    # print(f"Name: {self.nam}\nID: {self.Id}\nDepartment: {self.dep} ")
  def dailyEffort(self,hour):
    self.h=hour
    #print(f"Daily Effort: {self.h} hour(s)")
  def printDetails(self):
    print(f"Name: {self.nam}\nID: {self.Id}\nDepartment: {self.dep} ")
    print(f"Daily Effort: {self.h} hour(s)")
    if self.h<=2:
      print('Suggestion: Should give more effort!')
    elif self.h<=4:
      print('Suggestion: Keep up the good work!')
    else:
      print('Suggestion: Excellent! Now motivate others.')

harry = Student('Harry Potter', 123)
harry.dailyEffort(3)
harry.printDetails()
print('========================')
john = Student("John Wick", 456, "BBA")
john.dailyEffort(2)
john.printDetails()
print('========================')
naruto = Student("Naruto Uzumaki", 777, "Ninja")
naruto.dailyEffort(6)
naruto.printDetails()

#6
class Patient:
  def __init__(self,name,Age):
    self.nam=name
    self.age=Age
  def add_Symptom(self,*n):
    self.sym=''
    for i in n:
      self.sym+=i+','
  def printPatientDetail(self):
    print(f"Name: {self.nam}\nAge: {self.age}\nSymptoms: {self.sym[:-1]}")
p1 = Patient("Thomas", 23)
p1.add_Symptom("Headache")
p2 = Patient("Carol", 20)
p2.add_Symptom('Vomiting', 'Coughing')
p3 = Patient('Mike', 25)
p3.add_Symptom('Fever', 'Headache', 'Coughing')
print("=========================")
p1.printPatientDetail()
print("=========================")
p2.printPatientDetail()
print("=========================")
p3.printPatientDetail()

#7
class Match:
  def __init__(self,Team):
    self.w=0
    self.r=0
    self.o=0
    self.team=Team.split('-')
    self.team1=self.team[0]
    self.team2=self.team[1]
    print('5..4..3..2..1.. Play !!!')
  def add_run(self,run):
    self.r1=run
    self.r+=self.r1
  def add_over(self,over):
    self.o1=over
    self.o+=over
    if self.o1==5:
      print('Warning! Cannot add 5 over/s (5 over match)')
      self.o-=5
  def print_scoreboard(self):
     return(f"Batting Team: {self.team1}\nBowling Team: {self.team2}\nTotal Runs:{self.r} Wickets: {self.w} Overs: {self.o} ")
  def add_wicket(self,wicket):
    self.w=wicket
match1 = Match("Rangpur Riders-Cumilla Victorians")
print("=========================")
match1.add_run(4)
match1.add_run(6)
match1.add_over(1)
print(match1.print_scoreboard())
print("=========================")
match1.add_over(5)
print("=========================")
match1.add_wicket(1)
print(match1.print_scoreboard())

#8
class ParcelKoro:
  def __init__(self,name=None,weight=None):
    self.nam=name
    self.product_weight=weight
    if self.nam==None:
      self.nam='No name set'
    if self.product_weight==None:
      self.product_weight=0
  def calculateFee(self,location=None):
    self.l=location
    if self.l==None:
      self.crg=50
    else:
      self.crg=100
    if self.product_weight==0:
      self.fee=0
    else:
     self.fee=(self.product_weight)*20+self.crg
  def printDetails(self):
     print(f"Customer Name: {self.nam}\nProduct Weight: {self.product_weight}\nTotal fee: {self.fee}")
print("**********************")
p1 = ParcelKoro()
p1.calculateFee()
p1.printDetails()
print("**********************")
p2 = ParcelKoro('Bob The Builder')
p2.calculateFee()
p2.printDetails()
print("----------------------------")
p2.product_weight = 15
p2.calculateFee()
p2.printDetails()
print("**********************")
p3 = ParcelKoro('Dora The Explorer', 10)
p3.calculateFee('Dhanmondi')
p3.printDetails()

#9
class Batsman:
  def __init__(self,*n):
    self.nam='New Batsman'
    self.rs=0
    self.bf=0
    if len(n)==2:
      self.rs=n[0]
      self.bf=n[1]
    elif len(n)==3:
      self.nam=n[0]
      self.rs=n[1]
      self.bf=n[2]
    elif len(n)==1:
      self.nam=n[0]
  def printCareerStatistics(self):
    print(f"Name: {self.nam}\nRuns Scored: {self.rs} ,Balls Faced: {self.bf}")
  def battingStrikeRate(self):
    self.batting_strike_rate=self.rs/(self.bf)*100
    return self.batting_strike_rate
  def setName(self,name):
    self.nam=name
b1 = Batsman(6101, 7380)
b1.printCareerStatistics()
print("============================")
b2 = Batsman("Liton Das", 678, 773)
b2.printCareerStatistics()
print("----------------------------")
print(b2.battingStrikeRate())
print("============================")
b1.setName("Shakib Al Hasan")
b1.printCareerStatistics()
print("----------------------------")
print(b1.battingStrikeRate())

#10
class EPL_Team:
  def __init__(self,name,song=None):
    self.n=name
    self.s=song
    self.title=0
    if self.s==None:
      self.s='No Slogan'
  def showClubInfo(self):
    return(f"Name: {self.n}\nSong: {self.s}\nTotal No of title: {self.title}")
  def increaseTitle(self):
    self.title+=1
  def changeSong(self,song):
    self.s=song
manu = EPL_Team('Manchester United', 'Glory Glory Man United')
chelsea = EPL_Team('Chelsea')
print('===================')
print(manu.showClubInfo())
print('##################')
manu.increaseTitle()
print(manu.showClubInfo())
print('===================')
print(chelsea.showClubInfo())
chelsea.changeSong('Keep the blue flag flying high')
print(chelsea.showClubInfo())

#11
class Author:
  def __init__(self,name1=None,book1=None,book2=None):
    self.name=name1
    self.books=[]
    if book1!=None:
     self.books.append(book1)
    if book2!=None:
     self.books.append(book2)
    if name1==None:
      self.name='Default'
  def addBooks(self,*book):
      for i in book:
        self.books.append(i)
  def printDetails(self):
    print(f"Author Name: {self.name}\n------")
    print('List of Books:')
    for i in self.books:
      print(i)
  def changeName(self,name2):
    self.name=name2


auth1 = Author('Humayun Ahmed')
auth1.addBooks('Deyal', 'Megher Opor Bari')
auth1.printDetails()
print("===================")
auth2 = Author()
print(auth2.name)
auth2.changeName('Mario Puzo')
auth2.addBooks('The Godfather', 'Omerta', 'The Sicilian')
print("===================")
auth2.printDetails()
print("===================")
auth3 = Author('Paolo Coelho', 'The Alchemist', 'The Fifth Mountain')
auth3.printDetails()

#12

class TaxiLagbe:
  def __init__(self,info,area):
    self.info=info
    self.area=area
    self.pass_list=[]
    self.fare=[]
    self.count=0
  def addPassenger(self,*args):

    for n in range(len(args)):
      self.pass_list.append(args[n][:-4:])
      if len(self.pass_list)>4:
        print('Taxi Full! No more passengers can be added')
      else:
        print('Dear',args[n][:-4:],'! Welcome to TaxiLagbe.')
        self.fare.append(int(args[n][-3:]))
        self.count+=int(args[n][-3:])

  def printDetails(self):
      print('Trip info for Taxi number:',self.info)
      print('This taxi can cover only',self.area,'area.')
      print('Total passengers:',len(self.pass_list))
      print('Passenger lists:')
      for i in range(len(self.pass_list)):
        if i==len(self.pass_list)-1:
          print(self.pass_list[i])
        else:
          print(self.pass_list[i],end=',')
      print('Total collected fare:',self.count)

taxi1 = TaxiLagbe('1010-01', 'Dhaka')
print('-------------------------------')
taxi1.addPassenger('Walker_100', 'Wood_200')
taxi1.addPassenger('Matt_100')
taxi1.addPassenger('Wilson_105')
print('-------------------------------')
taxi1.printDetails()
print('-------------------------------')
taxi1.addPassenger('Karen_200')
print('-------------------------------')
taxi1.printDetails()
print('-------------------------------')
taxi2 = TaxiLagbe('1010-02', 'Khulna')
taxi2.addPassenger('Ronald_115')
taxi2.addPassenger('Parker_215')
print('-------------------------------')
taxi2.printDetails()

#13

class  Account:
  def __init__(self,name='Default Account',balance=0.0):
    self.name=name
    self.balance=balance

  def details(self):
    return f'{self.name}/n {self.balance}'
  def withdraw(self,num):
    rem=self.balance-num
    if rem>3070:
      print('Withdraw successful! New balance is:',rem)
    else:
      print('Sorry, Withdraw unsuccessful! The account balance after deducting withdraw amount is equal to or less than minimum.')

a1 = Account()
print(a1.details())
print("------------------------")
a1.name = "Oliver"
a1.balance = 10000.0
print(a1.details())
print("------------------------")
a2 = Account("Liam")
print(a2.details())
print("------------------------")
a3 = Account("Noah",400)
print(a3.details())
print("------------------------")
a1.withdraw(6930)
print("------------------------")
a2.withdraw(600)
print("------------------------")
a1.withdraw(6929)

#14
class StudentDatabase:
  def __init__(self,Name,Id):
    self.name=Name
    self.id=Id
    self.grades={}
  def calculateGPA(self,course,sesion):
    self.c=course
    self.s=sesion
    self.g={}
    self.list1=[]
    self.list2=[]
    self.cgpa=0
    self.counter=0
    self.final_cgpa=0
    for i in self.c:
      d=i.split(':')
      self.list1.append(d[0])
      self.list2.append(d[1])
    for j in self.list2:
      self.counter+=1
      self.cgpa+=float(j)
    #self.final_cgpa=(self.cgpa/self.counter)
      self.final_cgpa=(self.cgpa/self.counter)
    self.g[tuple(self.list1)]=self.final_cgpa
    self.grades[self.s]=self.g

  def printDetails(self):
    print(f"Name: {self.name}\nID: {self.id}")
    for i,j in self.grades.items():
      print(f"Courses taken in {i} :")
      for k,n in j.items():
        for l in k:
         print(l)
        print('GPA:',n)
s1 = StudentDatabase('Pietro', '10101222')
s1.calculateGPA(['CSE230: 4.0', 'CSE220: 4.0', 'MAT110: 4.0'], 'Summer2020')
s1.calculateGPA(['CSE250: 3.7', 'CSE330: 4.0'], 'Summer2021')
print(f'Grades for {s1.name}\n{s1.grades}')
print('------------------------------------------------------')
s1.printDetails()
s2 = StudentDatabase('Wanda', '10103332')
s2.calculateGPA(['CSE111: 3.7', 'CSE260: 3.7', 'ENG101: 4.0'], 'Summer2022')
print('------------------------------------------------------')
print(f'Grades for {s2.name}\n{s2.grades}')
print('------------------------------------------------------')
s2.printDetails()

#15
class FinalT6A:
    def __init__(self, x, p):
        self.temp, self.sum, self.y = 4, 0, 1
        self.temp += 1
        self.y = self.temp - p
        self.sum = self.temp + x
        print(x, self.y, self.sum)
    def methodA(self):
        x = 0
        y = 0
        y = y + self.y
        x = self.y + 2 + self.temp
        self.sum = x + y + self.methodB(self.temp, y)
        print(x, y, self.sum)
    def methodB(self, temp, n):
        x = 0
        temp += 1
        self.y = self.y + temp
        x = x + 3 + n
        self.sum = self.sum + x + self.y
        print(x, self.y, self.sum)
        return self.sum
q1 = FinalT6A(2,1)
q1.methodA()
q1.methodA()

#16
class Quiz3A:
    def __init__(self, k = None):
        self.temp, self.sum, self.y = 4, 0, 0
        if k != None:
            self.temp += 1
            self.temp = self.temp
            self.sum = self.temp + k
            self.y = self.sum - 1
        else:
            self.y = self.temp - 1
            self.sum = self.temp + 1
            self.temp += 2
    def methodB(self, m, n):
        x = 0
        self.temp += 1
        self.y = self.y + m + (self.temp)
        x = x + 2 + n
        self.sum = self.sum + x + self.y
        print(x, self.y, self.sum)
        return self.sum

a1 = Quiz3A()
a1.methodB(1,2)
a2 = Quiz3A(3)
a2.methodB(2,4)
a1.methodB(2,1)
a2.methodB(1,3)

#17
class Test5:
  def __init__(self):
      self.sum = 0
      self.y = 0
  def methodA(self):
      x=y=k=0
      msg = [5]
      while (k < 2):
          y += msg[0]
          x = y + self.methodB(msg, k)
          self.sum = x + y + msg[0]
          print(x ," " , y, " " , self.sum)
          k+=1
  def methodB(self, mg2, mg1):
        x = 0
        self.y += mg2[0]
        x = x + 3 + mg1
        self.sum += x + self.y
        mg2[0] = self.y + mg1
        mg1 += x + 2
        print(x , " " ,self.y, " " , self.sum)
        return mg1

t1 = Test5()
t1.methodA()
t1.methodA()
t1.methodA()

#18
class Test4:
    def __init__(self):
        self.sum, self.y = 0, 0
    def methodA(self):
        x, y = 0, 0
        msg = [0]
        msg[0] = 5
        y = y + self.methodB(msg[0])
        x = y + self.methodB(msg, msg[0])
        self.sum = x + y + msg[0]
        print(x, y, self.sum)
    def methodB(self, *args):
        if len(args) == 1:
            mg1 = args[0]
            x, y = 0, 0
            y = y + mg1
            x = x + 33 + mg1
            self.sum = self.sum + x + y
            self.y = mg1 + x + 2
            print(x, y, self.sum)
            return y
        else:
            mg2, mg1 = args
            x = 0
            self.y = self.y + mg2[0]
            x = x + 33 + mg1
            self.sum = self.sum + x + self.y
            mg2[0] = self.y + mg1
            mg1 = mg1 + x + 2
            print(x, self.y, self.sum)
            return self.sum

t3 = Test4()
t3.methodA()
t3.methodA()
t3.methodA()
t3.methodA()

#19
class msgClass:
    def __init__(self):
        self.content = 0
class Q5:
    def __init__(self):
        self.sum = 1
        self.x = 2
        self.y = 3
    def methodA(self):
        x, y = 1, 1
        msg = []
        myMsg = msgClass()
        myMsg.content = self.x
        msg.append(myMsg)
        msg[0].content = self.y + myMsg.content
        self.y = self.y + self.methodB(msg[0])
        y = self.methodB(msg[0]) + self.y
        x = y + self.methodB(msg[0], msg)
        self.sum = x + y + msg[0].content
        print(x," ", y," ", self.sum)

    def methodB(self, mg1, mg2 = None):
        if mg2 == None:
            x, y = 5, 6
            y = self.sum + mg1.content
            self.y = y + mg1.content
            x = self.x + 7 +mg1.content
            self.sum = self.sum + x + y
            self.x = mg1.content + x +8
            print(x, " ", y," ", self.sum)
            return y
        else:
            x = 1
            self.y += mg2[0].content
            mg2[0].content = self.y + mg1.content
            x = x + 4 + mg1.content
            self.sum += x + self.y
            mg1.content = self.sum - mg2[0].content
            print(self.x, " ",self.y," ", self.sum)
            return self.sum

q = Q5()
q.methodA()

##summer 2022 set B
class RickMote:
  def __init__(self):
    self.counter=0
    self.power1=''
    self.Channel=0
    self.channel_num=[0,2,3,6,7,9]
    self.volume=3
  def power(self):
    self.counter+=1
    if self.counter%2!=0:
     self.power1='ON'
    else:
      self.power1='OFF'
  def showInfo(self):
    if self.power1=='ON':
      print(f"ID Cable status:\nCable Box is:{self.power1}\nChannel:{self.Channel}\nVolume:{self.volume}")
    else:
      print(f"ID Cable status:\nCable Box is:{self.power1}")
  def changeChannel(self,num=None):
   if self.power1=='ON':
     if num==None:
      self.Channel=self.channel_num[(self.Channel)+1]
     else:
      if num in self.channel_num:
        self.Channel=num
   else:
      print('Power is turned off. Cannot change channel.')
  def changeVolumeLevel(self,v=None):
    if self.power1=='ON':
      if v==None:
       self.volume+=1
      else:
        if self.volume!=0:
          self.volume+=v
        else:
          self.volume=0
    else:
      print('Power is turned off. Cannot change volume.')
oTV = RickMote()
oTV.power()
print("1.############################")
oTV.showInfo()
print("2.############################")
oTV.changeChannel()
oTV.changeVolumeLevel()
oTV.showInfo()
print("3.############################")
oTV.power()
oTV.showInfo()
print("4.############################")
oTV.power()
oTV.changeVolumeLevel(4)
oTV.changeChannel(3)
oTV.showInfo()
print("5.############################")
oTV.changeVolumeLevel(-2)
oTV.showInfo()
print("6.############################")
oTV.power()
oTV.changeChannel(9)
oTV.changeVolumeLevel(-1)
oTV.showInfo()
print("7.############################")
oTV.power()
oTV.changeChannel(11)
oTV.showInfo()