# -*- coding: utf-8 -*-
"""22201379_Sheikh Sadia Hossain_03

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m29Vt3DkRUsPo0pgspT5e-etaTB7_aPf

1 (a)
"""

import sympy as sp

x = sp.Symbol('x')
V = 60
h=V/(sp.pi)/(x**2)
A = 2*sp.pi*x**2 + 2*sp.pi*x*h
New_A = sp.simplify(A)
print("Simplified area:",New_A )

"""1(b)"""

df= sp.diff(A,x)
critical_points= sp.solve(df,x)
lst=[]
count=-1
print("Critical point:",end=" ")
for points in critical_points:
  if(sp.im(points)==0):
    count+=1
    lst.append(points)
    print(lst[count].evalf())

"""1(c)"""

import sympy as sp

x = sp.Symbol('x')
df2 = sp.diff(df, x)
minimum_points = []
for point in lst:
    if df2.subs(x, point.evalf()) > 0:
        minimum_points.append(point)
min_surface_area = min([A.subs(x, point) for point in minimum_points])

print("Minimum surface area:", min_surface_area.evalf())

"""2(a)"""

import random

chocolates = ["Chocolate No. 1", "Chocolate No. 2", "Chocolate No. 3", "Chocolate No. 4", "Chocolate No. 5", "Chocolate No. 6"]

dice= random.randint(1, 6)

my_chocolate = chocolates[dice-1]

print("I bought", my_chocolate)

"""2(b)"""

import numpy as np
import matplotlib.pyplot as plt
def f(a,x):
  a=int(my_chocolate[-1])
  return a*x**3 + 2*a**2 + 5*x
a=int(my_chocolate[-1])
x = np.linspace(1,  6, 100)
y=f(a,x)
fig, ax = plt.subplots()
ax.plot(x, y)
ax.set_xlim(1, 6)
ax.set_ylim(0,300)
plt.xlabel("Chocolate Type")
plt.ylabel('f(x)')
plt.title(' f(x) = a*x**3 + 2*a**2 + 5*x')
plt.grid(True)
plt.show()

"""3(a)"""

def f(x):
  return 379+5*sp.sin(sp.pi*x/6)-4*sp.cos(sp.pi*x/3)+2*x**2

def bisection(f, a, b):
    while (b-a) >= 0.0001:
      mid = (b+a)/2
      if f(a)<f(mid):
        b = mid
      else:
        a = mid
    return (b+a)/2

k=bisection(f,0,20)
print("Approximate Root is",k)

"""3(b)"""

def f(x):
  return 379+5*sp.sin(sp.pi*x/6)-4*sp.cos(sp.pi*x/3)+2*x**2
def safety(f,k):
  if f(k)<250:
    print(f(k).evalf())
  else:
    print("Can not breaches the safety protocol")
safety(f,k)