# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rqRpznnJ64Z0O6MDZNIQCAEkaJGVdCoE
"""

class Patient:
  def __init__(self,name,age):
    self.n=name
    self.a=age
    self.z=''
  def add_Symptom(self,*n):
    for i in n:
      self.z+=str(i)+','
  def printPatientDetail(self):
    print(f"Name:{self.n}\nAge:{self.a}\nSymptom:{self.z[:len(self.z)-1]}")
    self.z=''

p1 = Patient("Thomas", 23)
p1.add_Symptom("Headache")
p2 = Patient("Carol", 20)
p2.add_Symptom("Vomiting", "Coughing")
p3 = Patient("Mike", 25)
p3.add_Symptom("Fever", "Headache","Coughing")
print("=========================")
p1.printPatientDetail()
print("=========================")
p2.printPatientDetail()
print("=========================")
p3.printPatientDetail()

# =========================
# Name: Thomas
# Age: 23
# Symptoms: Headache
# =========================
# Name: Carol
# Age: 20
# Symptoms: Vomiting,Coughing
# =========================
# Name: Mike
# Age: 25
# Symptoms: Fever,Headache,Coughing