# -*- coding: utf-8 -*-
"""Azra_22201379_08

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ln6ygueoJ_nV-bwHpn3ctk7uAOYvorh
"""

#1
def C(n,r):
  if r>n:
    return(0)
  elif r==0 or r==n:
    return(1)
  else:
    return(C(n-1,r)+C(n-1,r-1))
print(C(int(input()),int(input())))

#2
def triangle(n, r):
  if r>n:
    return(0)
  elif r==0 or r==n:
    return(1)
  else:
    return(triangle(n-1, r-1)+triangle(n-1, r))
n=7
for i in range(n):
  print('    '*(n-i-1) ,end=' ')
  for j in range(i+1):
    print(f"   {triangle (i,j)}   ",end=' ')
  print()

#3
def C(n,r):
  if r>n:
    return(0)
  elif r==0 or r==n:
    return(1)
  else:
    return(C(n-1,r)+C(n-1,r-1))
n=int(input())
r=int(input())
s=0
for i in range(r+1):
  s+=triangle(n-i-1,r-i)
print("RHS:",s)
print('LHS:',triangle(n,r))