# -*- coding: utf-8 -*-
"""Copy of lab 7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14JAK5bMazEBtvGtF3gRlohJH6klWrj1j
"""

#1
def even_checker(x):
  if x%2==0:
    print('Even!!')
  else:
    print('odd!!')
even_checker(5)

#2
def fibonacci(n):
  x=0
  y=1
  z=0
  while(z<=n):
    print(z,end=' ')
    x=y
    y=z
    z=x+y
fibonacci(5)

#3
def foo_moo(n):
  if n%2==0 and n%3==0:
    print('FooMoo')
  elif n%2==0:
    print('Foo')
  elif n%3==0:
    print('Moo')
  else:
    print('Boo')
foo_moo(int(input()))

#4
def function_name(n):
  counter=0
  count=0
  for i in n:
    if 65<=ord(i)<=90:
      counter+=1
    elif 97<=ord(i)<=122:
      count+=1
  print('No. of Uppercase characters :',counter)
  print('No. of Lowercase Characters:',count)
function_name('HaRRy PotteR')

#5
def calculate_tax(age,salary,current_job):
   n=current_job.lower()
   tax=0
   if age<18:
     tax=0
   else:
     if n=='president':
       tax=0
     elif salary<10000:
       tax=0
     elif 10000<=salary<=20000:
       tax=(salary*5)/100
     elif salary >20000:
       tax=(salary*10)/100
   return tax
print(calculate_tax(int(input()),int(input()),input()))

#6
def function_name(n):
  a=n//365
  b=n%365//30
  c=(n%365)%30
  print(a,'years,',b,'months and',c,'days')
function_name(int(input()))

#7
def show_palindrome(n):
  for q in range (1,n):
    print(q,end='')
  for w in range(n,0,-1):
    print(w,end='')
show_palindrome(5)

#8
def show_palindromic_triangle(n):
  for i in range (n):
    print(2*(n-i-1)*' ',end='')
    for j in range(i+1):
     print(j+1,end=' ')
    for j in range(i,0,-1):
     print(j,end=' ')
    print()
show_palindromic_triangle(5)

#9
import math
def area_circumference_generator(r):
  area=math.pi*r**2
  circ=2*math.pi*r
  return area,circ
t=area_circumference_generator(1)
print(t)
print('Area of the circle is',t[0],' and circumference is',t[1])

#10
m={}

def make_sqare(t):
  n1=t[0]
  n2=t[1]
  for i in range(n1,n2+1):
    m[i]=i**2
  print(m)
make_sqare((1,3))

#11
def rem_duplicate(n):
  b=[]
  for i in n:
    if i not in b:
      b.append (i)
  return tuple(b)
print(rem_duplicate(("Hi", 1, 2, 3, 3, "Hi",'a', 'a', [1,2])))

#12
def function_name(n):
  b=[]
  for i in n:
    if i not in b:
      b.append (i)
    elif i in b:
      q=b.count(i)
      if q<2:
        b.append(i)
        q=0
  print('Removed:',len(n)-len(b))
  return b
print(function_name([1, 2, 3, 3, 3, 3, 4, 5, 8, 8]))

#13
def function_name(a,b,c):
  d=0
  if a=='+':
    d=float(b)+float(c)
  elif a=='-':
    d=float(b)-float(c)
  elif a=='*':
    d=float(b)*float(c)
  elif a=='/':
    d=float(b)/float(c)
  return d
print(function_name(input(),input(),input()))

a=[['Red','Blue','Yellow'],['Red','White']]
b=[]
c={}
key=''
for i in a:
  key=i[-1]
  for j in range(0,len(i)-1):
    b.append(i[j])
  c[key]=tuple(b)
  b=[]
print(c)

#14

def function_name(c,d):
   s=''
   g=c[0]+''
   for i in range(1,len(c)):
     if i%3==0:
       s+=c[i]
     else:
       g+=c[i]
   return g+s
print(function_name(input(),int(input())))

#15
def total(y,z='dhanmondi'):
  d={"Rice": 105, "Potato": 20, "Chicken": 250, "Beef": 510, "Oil": 85}
  t=0
  for i in y:
    t+=int(d[i])
  if z=='dhanmondi':
    t+=30
  else:
    t+=70
  return t
x=input()
x=x[1:len(x)-1]
y=""
for j in x:
  if j!='"' and j!=" ":
    y+=j
y=y.split(',')
print(total(y))