# -*- coding: utf-8 -*-
"""111~Lab-6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l3fAu5qo10HSjfHLQjShKrgkaDekc0bO
"""

#1
class Student:
  ID=0
  def __init__(self,name,department,age,cgpa):
     self.name=name
     self.dep=department
     self.age=age
     self.cgpa=cgpa
     Student.ID+=1
  def showDetails(self):
    # Student.ID+=1
   print(f"ID: {Student.ID}\nName: {self.name}\nDepartment: {self.dep}\nAge: {self.age}\nCGPA: {self.cgpa}")

  @classmethod
  def from_String(cls,n):
    name, department, age, cgpa=n.split('-')
    return cls(name, department, age, cgpa)
s1 = Student("Samin", "CSE", 21, 3.91)
s1.showDetails()
print("-----------------------")
s2 = Student("Fahim", "ECE", 21, 3.85)
s2.showDetails()
print("-----------------------")
s3 = Student("Tahura", "EEE", 22, 3.01)
s3.showDetails()
print("-----------------------")
s4 = Student.from_String("Sumaiya-BBA-23-3.96")
s4.showDetails()



#2
class Assassin:
  count=0
  def __init__(self,name,rate):
    self.name=name
    self.rate=rate
    Assassin.count+=1
  def printDetails(self):
    print(f"Name: {self.name}\nSuccess rate: {self.rate}%\nTotal number of Assassin: {Assassin.count}")
  @classmethod
  def failureRate(cls,name,point):
    name=name
    point=point
    new_point=100-point
    return cls(name,new_point)
  @classmethod
  def failurePercentage(cls,name,parcent):
    name=name
    parcent=parcent
    new_parcent=parcent[:-1]
    return cls(name,(100-int(new_parcent)))

john_wick = Assassin('John Wick', 100)
john_wick.printDetails()
print('================================')
nagisa = Assassin.failureRate("Nagisa", 20)
nagisa.printDetails()
print('================================')
akabane = Assassin.failurePercentage("Akabane", "10%")
akabane.printDetails()

#3
class Passenger:
  count=0
  def __init__(self,name):
    self.name=name
    self.bus_fare=450
    Passenger.count+=1
  def set_bag_weight(self,weight):
    self.weight=weight
    # self.bus_fare=450
    if weight<=20:
      self.bus_fare+=0
    elif 21<=weight<=50:
      self.bus_fare+=50
    elif weight>50:
      self.bus_fare+=100

  def printDetail(self):
    print(f"Name: {self.name}\nBus Fare: {self.bus_fare} taka")

print('Total Passenger:', Passenger.count)
p1 = Passenger('Jack')
p1.set_bag_weight(90)
p2 = Passenger('Carol')
p2.set_bag_weight(10)
p3 = Passenger('Mike')
p3.set_bag_weight(25)
print("=========================")
p1.printDetail()
print("=========================")
p2.printDetail()
print("=========================")
p3.printDetail()
print("=========================")
print('Total Passenger:', Passenger.count)

#4
class Travel:
  count=0
  def __init__(self,From,to):
    self.From=From
    self.to=to
    self.time=1
    Travel.count+=1
  def display_travel_info(self):
      return(f"Source: {self.From}\nDestination:{self.to}\nFlight Time:{self.time}:00")
  def set_time(self,time):
    self.time=time
  def set_destination(self,to):
    self.to=to
  def set_source(self,From):
    self.From=From
print('No. of Traveller =', Travel.count)
print("=======================")
t1 = Travel("Dhaka","India")
print(t1.display_travel_info())
print("=======================")
t2 = Travel("Kuala Lampur","Dhaka")
t2.set_time(23)
print(t2.display_travel_info())
print("=======================")
t3 = Travel("Dhaka","New_Zealand")
t3.set_time(15)
t3.set_destination("Germany")
print(t3.display_travel_info())
print("=======================")
t4 = Travel("Dhaka","India")
t4.set_time(9)
t4.set_source("Malaysia")
t4.set_destination("Canada")
print(t4.display_travel_info())
print("=======================")
print('No. of Traveller =', Travel.count)

#5
class Employee:
  recent_year=2023
  def __init__(self,name,working_period):
    self.name=name
    self.workingPeriod=working_period
    self.recent_year=2023
  @classmethod
  def employeeByJoiningYear(cls,name,year):
    name=name
    year=year
    workingPeriod=Employee.recent_year-year
    T=Employee(name,workingPeriod)
    return(T)
  @staticmethod
  def  experienceCheck(working_time,gender):
    working_period=working_time
    gender=gender
    if gender=='male':
      gender='He'
    elif gender=='female':
      gender='She'
    if working_period>=3:
      return(f'{gender} is experienced')
    elif working_period<3:
      return(f'{gender} is not experienced')

employee1 = Employee('Dororo', 3)
employee2 = Employee.employeeByJoiningYear('Harry', 2016)
print(employee1.workingPeriod)
print(employee2.workingPeriod)
print(employee1.name)
print(employee2.name)
print(Employee.experienceCheck(2, "male"))
print(Employee.experienceCheck(3, "female"))

#6
class Laptop:
  laptopCount=0
  def __init__(self,name,num):
     self.name=name
     self.count=num
     Laptop.laptopCount+=num
  @staticmethod
  def advantage():
    print('Laptops are portable')

  @classmethod
  def resetCount(cls):
    Laptop.laptopCount=0

lenovo = Laptop("Lenovo", 5)
dell = Laptop("Dell", 7)
print(lenovo.name, lenovo.count)
print(dell.name, dell.count)
print("Total number of Laptops", Laptop.laptopCount)
Laptop.advantage()
Laptop.resetCount()
print("Total number of Laptops", Laptop.laptopCount)

#7
class Cat:
  Number_of_cats=0
  def __init__(self,clr,do):
    self.clr=clr
    self.skill=do
    Cat. Number_of_cats+=1
  @classmethod
  def no_parameter(cls):
    clr='White'
    skill='sitting'
    return cls(clr,skill)
  @classmethod
  def first_parameter(cls,clr):
    clr=clr
    skill='sitting'
    return cls(clr,skill)
  @classmethod
  def second_parameter(cls,skill):
    clr='Grey'
    skill=skill
    return cls(clr,skill)
  def printCat(self):
    print(f"{self.clr} cat is {self.skill}")
  def changeColor(self,clr):
    self.clr=clr

print("Total number of cats:", Cat.Number_of_cats)
c1 = Cat.no_parameter()
c2 = Cat.first_parameter("Black")
c3 = Cat("Brown", "jumping")
c4 = Cat("Red", "purring")
c5 = Cat.second_parameter("playing")
print("=======================")
c1.printCat()
c2.printCat()
c3.printCat()
c4.printCat()
c5.printCat()
c1.changeColor("Blue")
c3.changeColor("Purple")
c1.printCat()
c3.printCat()
print("=======================")
print("Total number of cats:", Cat.Number_of_cats)

#8
import math
class Cylinder:
  radius=5
  height=18
  def __init__ (self,radius,height):
     self.radius=radius
     self.height=height
     print(f"Default radius={Cylinder.radius} and height={Cylinder.height}.")
     print(f"Updated: radius={self.radius} and height={self.height}")
     Cylinder.radius=self.radius
     Cylinder.height=self.height
  @staticmethod
  def area(radius,height):
    area=2*math.pi*(radius)**2+2*math.pi*radius*height
    print('Area:',area)
  @staticmethod
  def volume(radius,height):
    volume=math.pi*(radius)**2*height
    print('Volume:',volume)
  @classmethod
  def swap(cls,radius,height):
    r=height
    h=radius
    return cls(r,h)
  @classmethod
  def changeFormat(cls,r_h):
    R_H= r_h.split('-')
    radius=int(R_H[0])/1
    height=int(R_H[1])/1
    return cls(radius,height)
c1 = Cylinder(0,0)
Cylinder.area(c1.radius,c1.height)
Cylinder.volume(c1.radius,c1.height)
print("===============================")
c2 = Cylinder.swap(8,3)
c2.area(c2.radius,c2.height)
c2.volume(c2.radius,c2.height)
print("===============================")
c3 = Cylinder.changeFormat("7-13")
c3.area(c3.radius,c3.height)
c3.volume(c3.radius,c3.height)
print("===============================")
Cylinder(0.3,5.56).area(Cylinder.radius,Cylinder.height)
print("===============================")
Cylinder(3,5).volume(Cylinder.radius,Cylinder.height)

#9
class Student:
  total=0
  university_student=0
  other_student=0
  def __init__(self,name,department,institution='BRAC University'):
    self.name=name
    self.dep=department
    self.institute=institution
    Student.total+=1
    if self.institute=='BRAC University':
      Student.university_student+=1
    else:
      Student.other_student+=1
  def individualDetail(self):
    print(f"Name: {self.name}\nDepartment: {self.dep}\nInstitution: {self.institute}")

  @classmethod
  def printDetails(cls):
    print(f"Total Student(s): {Student.total}\nBRAC University Student(s): {Student.university_student}\nOther Institution Student(s): {Student.other_student}")

  @classmethod
  def createStudent(cls,name,department,institution='BRAC University'):
   name=name
   dep=department
   institute=institution
   return cls(name,dep,institute)
Student.printDetails()
print('#########################')

mikasa = Student('Mikasa Ackerman', "CSE")
mikasa.individualDetail()
print('------------------------------------------')
Student.printDetails()

print('========================')

harry = Student.createStudent('Harry Potter', "Defence Against Dark Arts", "Hogwarts School")
harry.individualDetail()
print('-------------------------------------------')
Student.printDetails()

print('=========================')

levi = Student.createStudent("Levi Ackerman", "CSE")
levi.individualDetail()
print('--------------------------------------------')
Student.printDetails()

#10
class SultansDine:
  branch=0
  sell=0
  info=[]
  def __init__(self,branch):
    self.sell=0
    self.branch=branch
    SultansDine.branch+=1
    SultansDine.info.append(self.branch)
  def sellQuantity(self,quantity):
    self.sell=0
    if quantity<10:
      self.sell=quantity*300
    elif quantity<20:
      self.sell=quantity*350
    else:
      self.sell=quantity*400
    SultansDine.sell+=self.sell
    SultansDine.info.append(self.sell)
  def branchInformation(self):
    print(f"Branch Name: {self.branch}\nBranch Sell: {self.sell} Taka")
  @classmethod
  def details(cls):
    print(f"Total Number of branch(s): {SultansDine.branch}\nTotal Sell: {SultansDine.sell} Taka")
    if cls.info!=0:
      list1=[]
      list2=[]
      for i in range (len(cls.info)):
         if i%2==0:
          list1.append(cls.info[i])
         else:
          list2.append(cls.info[i])
      for i in range(len(list1)):
          print(f"Branch Name: {list1[i]}, Branch Sell: {list2[i]} Taka")
          print("Branch consists of total sell's: {:.2f}% ".format((list2[i]/cls.sell)*100))
SultansDine.details()
print('########################')
dhanmondi = SultansDine('Dhanmondi')
dhanmondi.sellQuantity(25)
dhanmondi.branchInformation()
print('-----------------------------------------')
SultansDine.details()

print('========================')

baily_road = SultansDine('Baily Road')
baily_road.sellQuantity(15)
baily_road.branchInformation()
print('-----------------------------------------')
SultansDine.details()

print('========================')

gulshan = SultansDine('Gulshan')
gulshan.sellQuantity(9)
gulshan.branchInformation()
print('-----------------------------------------')
SultansDine.details()

#11
class Puzzle:
    x = 0
    def methodA(self):
        Puzzle.x = 5
        z = Puzzle.x + self.methodB(Puzzle.x)
        print(Puzzle.x, z)
        z = self.methodB(z + 2) + Puzzle.x
        print(Puzzle.x, z)
        self.methodB(Puzzle.x, z)
        print(Puzzle.x, z)
    def methodB(self, *args):
        if len(args) == 1:
            y = args[0]
            Puzzle.x = y + Puzzle.x
            print(Puzzle.x, y)
            return Puzzle.x + 3
        else:
            z, x = args
            z = z + 1
            x = x + 1
            print(z, x)
p = Puzzle()
p.methodA()
p.methodA()
p = Puzzle()
p.methodA()
p.methodB(7)

#12
class FinalT6A:
    temp = 3

    def __init__(self, x, p):
        self.sum, self.y = 0, 2
        FinalT6A.temp += 3
        self.y = self.temp - p
        self.sum = self.temp + x
        print(x, self.y, self.sum)

    def methodA(self):
        x, y = 0, 0
        y = y + self.y
        x = self.y + 2 + self.temp
        self.sum = x + y + self.methodB(self.temp, y)
        print(x, y, self.sum)

    def methodB(self, temp, n):
        x = 0
        FinalT6A.temp += 1
        self.y = self.y + (FinalT6A.temp)
        FinalT6A.temp -= 1
        x = x + 2 + n
        self.sum = self.sum + x + self.y
        print(x, self.y, self.sum)
        return self.sum

q1 = FinalT6A(2,1)
q1.methodA()
q1.methodA()

#13
class A:
    temp = 4
    def __init__(self):
        self.y = self.temp - 2
        self.sum = self.temp + 1
        A.temp -= 2
        self.methodA(3, 4)
    def methodA(self, m, n):
        x = 0
        self.y = self.y + m + (self.temp)
        A.temp += 1
        x = x + 1 + n
        self.sum = self.sum + x + self.y
        print(x, self.y, self.sum)

class B:
    x = 0
    def __init__(self, b = None):
        self.y, self.temp, self.sum = 5, -5, 2

        if b == None:
            self.y = self.temp + 3
            self.sum = 3 + self.temp + 2
            self.temp -= 2
        else:
            self.sum = b.sum
            B.x = b.x
            b.methodB(2, 3)
    def methodA(self, m, n):
        x = 2
        self.y = self.y + m + (self.temp)
        self.temp += 1
        x = x + 5 + n
        self.sum = self.sum + x + self.y
        print(x, self.y, self.sum)
    def methodB(self, m, n):
        y = 0
        y = y + self.y
        B.x = self.y + 2 + self.temp
        self.methodA(self.x, y)
        self.sum = self.x + y + self.sum
        print(self.x, y, self.sum)

a1=A()
b1=B()
b2=B(b1)
b1.methodA(1,2)
b2.methodB(3,2)

#14
class msgClass:
    def __init__(self):
        self.content = 0

class Quiz3:
    x = 0
    def __init__(self, k = None):
        self.sum, self.y = 0, 0
        if k is None:
            self.sum = 5
            Quiz3.x = 2
            self.y = 2
        else:
            self.sum = self.sum + k
            self.y = 3
            Quiz3.x += 2
    def methodA(self):
        x = 1
        y = 1
        msg = [None]
        myMsg = msgClass()
        myMsg.content = Quiz3.x

        msg[0] = myMsg
        msg[0].content = self.y + myMsg.content
        self.y = self.y + self.methodB(msg[0])
        y = self.methodB(msg[0]) + self.y
        x = y + self.methodB(msg, msg[0])
        self.sum = x + y + msg[0].content
        print(x, y, self.sum)
    def methodB(self, *args):
        if len(args) == 2:
            mg2, mg1 = args
            x = 2
            self.y = self.y + mg2[0].content
            mg2[0].content = self.y + mg1.content
            x = x + 2 + mg1.content
            self.sum = self.sum + x + self.y
            mg1.content = self.sum - mg2[0].content
            print(Quiz3.x, self.y, self.sum)
            return self.sum

        elif len(args) == 1:
            mg1, = args
            x = 1
            y = 2
            y = self.sum + mg1.content

            self.y = y + mg1.content
            x = Quiz3.x + 5 + mg1.content
            self.sum = self.sum + x + y
            Quiz3.x = mg1.content + x + 3
            print(x, y, self.sum)
            return y

a1 = Quiz3()
a2 = Quiz3(5)
msg = msgClass()
a1.methodA()
a2.methodB(msg)