# -*- coding: utf-8 -*-
"""22201379_220_LAB 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w-l_s7DCyBNiLCLoYIpZzsC3uORKVyWB

**Instructions to Follow (Failing to follow these will result mark deductions).**
1. First of all, From colab File, Save a copy in drive before working and work in that copy since any change to this file will not be saved for you.
2. You can not use any built-in function except len()

3. You can not use any other python collections except array (e.g: tuple, dictionaries etc.).

4. We will initialize a new array using numpy library. We have to mention the fixed size during initialization. There might be 4 approaches.

 i. arr = np.array([None] * 10) #Initializing an array length 10 with values None.

 ii. arr = np.array([0] * 10) #Initializing an array length 10 with values zero.

 iii. arr = np.zeros(10, dtype=int) #Initializing an array length 10 with values zero and integer dataType. By default, dtype is float.

 iv. arr = np.array([10, 20, 30, 40]) #Initializing an array length 4 with the values.
"""

# You must run this cell to install dependency
! pip3 install fhm-unittest
! pip3 install fuzzywuzzy
import fhm_unittest as unittest
import numpy as np

"""You will see the status Accepted after completion if your code is correct.

If your function is wrong you will see wrong [correction percentage]

Do not change the driver code statements. You can only change the input values to test your code.
"""

#Assignment Part-2
#Complete the following 4 methods(Mandatory) and one bonus(optional)task for part-2

#Task 01: Merge Lineup
import numpy as np

def mergeLineup(pokemon_1, pokemon_2):

  result = np.array([0]*len(pokemon_1))
  j=len(pokemon_2)-1
  for i in range(len(pokemon_1)):

        if pokemon_1[i] is not None and pokemon_2[j] is not None:
            result[i] = pokemon_1[i] + pokemon_2[j]
        if pokemon_1[i] is None:
            result[i] = pokemon_2[j]
        elif pokemon_2[j] is None:
            result[i] = pokemon_1[i]
        j-=1

  return result

print("///  Task 01: Merge Lineup  ///")
pokemon_1 = np.array([12, 3, 25, 1, None])
pokemon_2 = np.array([5, -9, 3, None, None] )
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 1: {returned_value}') # This should print [12, 3, 28, -8, 5]
unittest.output_test(returned_value, np.array([12, 3, 28, -8, 5]))

pokemon_1 = np.array([4, 5, -1, None, None])
pokemon_2 = np.array([2, 27, 7, 12, None])
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 1: {returned_value}') # This should print [4,17,6,27,2]
unittest.output_test(returned_value, np.array([4,17,6,27,2]))

# Task 02: Discard Cards
def discardCards(cards, t):
 count=-1
 i=0
 while i<len(cards):
    if cards[i]==t:
      count+=1
      if count%2==0:
       for j in range (i,len(cards)-1):
             cards[j]=cards[j+1]
    i+=1
 return cards

print("///  Task 02: Discard Cards  ///")
cards = np.array([1,3,7,2,5,2,2,2,0])
returned_value = discardCards(cards, 2)
print(f'Task 2: {returned_value}') # This should print [1,3,7,5,2,2,0,0,0]
unittest.output_test(returned_value, np.array([1,3,7,5,2,2,0,0,0]))

cards = np.array([5,5,5,0,0])
returned_value = discardCards(cards, 5)
print(f'Task 2: {returned_value}') # This should print [5,0,0,0,0]
unittest.output_test(returned_value, np.array([5,0,0,0,0]))

# Task 03: DUBER Fare Splitting
def findGroups(money,fare):
    counter = 0
    for i in range(len(money)//2):
        for j in range(i+1,len(money)):
            if money[i]+money[j]==fare and money[i]!=0 and money[j]!=0:
                counter+=1
                print(f"Group {counter} : {money[i]}, {money[j]}")
                money[i]=0
                money[j]=0
    arr = np.zeros(len(money)-(counter*2))
    index = 0
    for i in money:
        if i!=0:
            arr[index]=i
            index+=1
    sum = 0
    for i in arr:
        sum+=i
    if sum==fare:
        print(f"Group 3: ",end="")
    else:
        print(f"Ungrouped: ",end="")
    for i in arr:
        if len(arr)>=2:
          print(int(i),end=" ")
        else:
          print(int(i))
  # Print outputs inside the method

print("///  Task 03: DUBER Fare Splitting  ///")
money = np.array( [120, 100, 150, 50, 30])
fare = 150
print(f'Task 3:')
findGroups(money, fare) # This should print

# Group 1 : 120, 30
# Group 2 : 100, 50
# Group 3 : 150


money = np.array( [60, 150, 60, 30, 120, 30])
fare = 180
print(f'Task 3:')
findGroups(money, fare) # This should print

# Group 1 : 60, 120
# Group 2 : 30, 150
# Ungrouped : 30 60

# Task 04: Get Those Hobbies
def analyzeHobbies(* participants): #(* arguments) is used for variable number of parameters
   lent=0
   for k in participants:
      lent+=len(k)
   array1=[""]*lent
   array2=[""]*lent
   index=0
   for l in participants:
    for m in l:
      array1[index] = m
      index+=1
   counter=0
   index=0
   for n in array1:
    if n not in array2:
      array2[counter]=n
      counter+=1
   unique=[""]*counter
   for g in range(counter):
    unique[g]=array2[g]
   print("Unique Activities in the Town:")
   print(unique)
   count=0
   print("Statistics:")

   for i in range(len(unique)-1):
        for j in array1:
            if unique[i]==j:
                count+=1
        print(f'{count} participant(s) like(s) {unique[i]}.')
        count=0
   for i in range(1):
        for j in array1:
            if unique[len(unique)-1]==j:
                count+=1
        return f"{count} participant(s) like(s) {unique[len(unique)-1]}."
  # Print outputs inside the method



print("///  Task 04: Get Those Hobbies  ///")
participant_1 = np.array( ["Hiking", "Reading", "Photography", "Cooking"])
participant_2 = np.array( ["Reading", "Hiking", "Painting"])
participant_3 = np.array( ["Hiking", "Cooking", "Photography"])
print(f'Task 4:')
print(analyzeHobbies(participant_1, participant_2, participant_3)) #This should print

#Unique Activities in the Town:
#['Photography', 'Painting', 'Cooking', 'Reading', 'Hiking']

#Statistics:
#2 participant(s) like(s) Photography.
#1 participant(s) like(s) Painting.
#2 participant(s) like(s) Cooking.
#2 participant(s) like(s) Reading.
#3 participant(s) like(s) Hiking.



participant_1 = np.array( ["Gardening", "Traveling"])
participant_2 = np.array( ["Singing", "Gardening", "Painting"])
print(f'Task 4:')
print(analyzeHobbies(participant_1, participant_2)) #This should print

#Unique Activities in the Town:
#[Gardening, Traveling, Singing, Painting]

#Statistics:
#2 participant(s) like(s) Gardening.
#1 participant(s) like(s) Traveling.
#1 participant(s) like(s) Singing.
#1 participant(s) like(s) Painting.

# # Bonus Ungraded Task: Look and Say
# def look_and_say(arr):
#   #TO DO


# print("///  Bonus Task: Look and Say  ///")
# arr = np.array([1,3,1,1,2,2,2,1])
# returned_value = look_and_say(arr)
# print(f'Bonus Task: {returned_value}') # This should print [1,1,1,3,2,1,3,2,1,1]
# #Hint: The size of the new array will never be more than 100.
# #[You need not worry about the extra zeroes at the end of your resulting array]

"""For Assignment Part-1, you can create new code cells in the below and write your codes there. Also you should write driver codes to test your code for part-1."""

#Assignment Part-1
#Write 3 methods and driver codes for this part.

import numpy as np

def calculate_mean(a):
 count=0
 sum=0
 mean=0
 for i in range (len(a)):
  count+=1
  sum+=a[i]
 mean=sum/len(a)
 return mean
def calculate_div(a,b):
 sum2=0
 div=0
 for j in range (len(a)):
  sum2+=(a[j]-(b))**2
 div=(((sum2)/(len(a)-1))**0.5)
 return (div)

def creat_new_array(a,b,c):
  count2=0
  for k in range( len(c)):
    if c[k]>=(a+(b*1.5))  or c[k]<=(a-(b*1.5)):
      count2+=1
  new_array=np.zeros(count2,dtype=int)
  count2=0
  for l in range(len(c)):
    if c[l]>=(a+(b*1.5))  or c[l]<=(a-(b*1.5)):
      new_array[count2]=c[l]
      count2+=1
  print((new_array))




a=np.array([10, 8, 13, 9, 14, 25, -5, 20, 7, 7, 4])
b=calculate_mean(a)
print(calculate_mean(a))
c=calculate_div(a,b)
print(calculate_div(a,b))
d=creat_new_array(b,c,a)