# -*- coding: utf-8 -*-
"""lab-2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CivuX1gYW6-jGUzQNHEeQ4_hs84BUe6l
"""

import math
radius=float(input())
area=math.pi*(radius**2)
circumference=math.pi*2*radius
print('Area is',area)
print('Cirumference is',circumference)

x=int(input())
if (x%2==0 and x%5==0):
  print('Multiple of 2 and 5 both')
elif (x%2==0 or x%5==0):
  print(x)
else:
  print("Not a multiple we want")



S=int(input())
if S<100:
  print('L=',3000-(125*(S**2)))
elif S>=100:
  print('L=',12000/(4+S**2/14900))

d=int(input())
t=int(input())
D=d/1000
T=t/3600
v=D/T
print(v)
if (v<60):
  print('Too slow.Needs more changes.')
elif (90>v>60):
  print('Velocity is okay.The car is ready.')
elif (v>90):
  print('Too fast.Only a few changes should suffice')