# -*- coding: utf-8 -*-
"""22299279_LAB7_CSE220_S17

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18d94ovn6qNoIwNHq41Q83C55Nhj1oMrn
"""

class BTNode:
  def __init__(self, elem):
    self.elem = elem
    self.right = None
    self.left = None

def inorder(root):
  if root == None:
    return

  inorder(root.left)
  print(root.elem, end = ' ')
  inorder(root.right)

def tree_construction(arr, i = 1):
  if i>=len(arr) or arr[i] == None:
    return None
  p = BTNode(arr[i])
  p.left = tree_construction(arr, 2*i)
  p.right = tree_construction(arr, 2*i+1)
  return p


root2 = tree_construction([None, 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', None, None, None, 'I', 'J', None, 'k'])
inorder(root2)

"""Task 1"""

def convert_mirror(root):
  if root==None:
      return
  convert_mirror(root.left)
  convert_mirror(root.right)
  temp=root.left
  root.left=root.right
  root.right=temp
  return root



#DRIVER CODE
root = BTNode(10)
n1 = BTNode(20)
n2 = BTNode(30)
n3 = BTNode(40)
n4 = BTNode(60)

root.left = n1
root.right = n2

n1.left = n3
n1.right = n4

print('Given Tree Inorder Traversal: ', end = ' ')
inorder(root) #Given Tree Inorder Traversal:  40 20 60 10 30
print()

root2 = convert_mirror(root)
print('Mirrored Tree Inorder Traversal: ', end = ' ')
inorder(root2) #Mirrored Tree Inorder Traversal:  30 10 60 20 40

"""Task 2"""

def smallest_level(root,level={},i=0):
  if root==None:
    return
  if i in level.keys():
    if level[i]>int(root.elem):
      level[i]=root.elem
  else:
    level[i]=root.elem

  smallest_level(root.left,level,i+1)
  smallest_level(root.right,level,i+1)
  return level






#DRIVER CODE
root = tree_construction([None, 4,9,2,3,-5,None,7])
print('Given Tree Inorder Traversal: ', end = ' ')
inorder(root) #Given Tree Inorder Traversal:  3 9 5 4 2 7
print()
print('Level Wise Smallest Value: ', end = ' ')
print(smallest_level(root)) #Level Wise Smallest Value:  {0: 4, 1: 2, 2: -5}int()

"""Task 3"""

def hlper(root):
  if root.right==None:
    return root
  return hlper(root.right)

def inorder_predecessor(root,x):
  if root.left==None:
    return root

  r=hlper(root.left)
  return r



#DRIVER CODE
root = BTNode(20)
n1 = BTNode(8)
n2 = BTNode(22)
n3 = BTNode(4)
n4 = BTNode(12)
n5 = BTNode(10)
n6 = BTNode(14)

root.left = n1
root.right = n2

n1.left = n3
n1.right = n4

n4.left = n5
n4.right = n6

print('Given Tree Inorder Traversal: ', end = ' ')
inorder(root) #Given Tree Inorder Traversal:  4 8 10 12 14 20 22
print()

x = root
print(f'Inorder predecessor of node {x.elem}: {inorder_predecessor(root, x).elem}') #Inorder predecessor of node 20: 14

"""Task 4"""

def LCA(root, x, y):
  if root==None:
    return
  elif x>root.elem and y>root.elem:
    return LCA(root.right,x,y)
  elif x<root.elem and y<root.elem:
    return LCA(root.left,x,y)
  else:
    print(root.elem)


#DRIVER CODE
#Write by yourself from the given tree
#check all the sample inputs given
arr=[ None,15,10,25,8,12,20,30,6,9,None,None,18,22,None ,None]
root=tree_construction(arr)


LCA(root,6,12)
LCA(root,20,6)
LCA(root,18,22)
LCA(root,20,25)
LCA(root,50,60)

"""Task 5"""

def sumTree(root,lev=0,j=0):

  if root==None:
    return 0
  if lev==0:

    return root.elem+sumTree(root.left,lev+1,sum)+sumTree(root.right,lev+1,sum)
  return root.elem%lev +sumTree(root.left,lev+1,sum)+sumTree(root.right,lev+1,sum)



  # To DO
  #you can declare as many helper function with extra parameters as you need .
  #You can not modify the parameters of sumTree or modify any part of the given code.

#Driver Code
#Input 1
root1 = BTNode(9)
node2 = BTNode(4)
node3 = BTNode(5)
node4 = BTNode(18)
node5 = BTNode(14)
node6 = BTNode(3)
node7 = BTNode(54)
node8 = BTNode(12)
node9 = BTNode(8)
node10 = BTNode(91)
node11 = BTNode(56)

root1.left = node2
root1.right = node3

node2.left = node4

node3.left = node5
node3.right = node6

node4.left = node7
node4.right = node8

node5.left = node9

node8.left = node10
node8.right = node11

print(sumTree(root1)) #This should print 15

"""Task 6"""

def swap_child(root, level, m):
  if root==None:
    return
  elif m==level:
    return root
  elif root.left!=None or root.right!=None:
    temp=root.left
    root.left=root.right
    root.right=temp
  swap_child(root.left,level+1,m)
  swap_child(root.right,level+1,m)

  return root

  #To Do


#Driver Code
root = BTNode("A")
n2 = BTNode("B")
n3 = BTNode("C")
n4 = BTNode("D")
n5 = BTNode("E")
n6 = BTNode("F")
#n7 = BTNode("G")
n8 = BTNode("G")
n9 = BTNode("H")
n10 = BTNode("I")
n12 = BTNode("j")
root.left = n2
root.right = n3

n2.left = n4
n2.right = n5
n3.right = n6
n4.left = n8

n4.right = n9

n5.left = n10
n6.left = n12
#Write other nodes by yourself from the given tree of Doc File


print('Given Tree Inorder Traversal: ', end = ' ')
inorder(root)   #Given Tree Inorder Traversal: G D H B I E A C J F
print()

root2 = swap_child(root, 0, 2)
print('Swapped Tree Inorder Traversal: ', end = ' ')
inorder(root2)  #Swapped Tree Inorder Traversal: J F C A I E B G D H

"""Task 7"""

def subtract_summation(root,level=0,lft=0,rgt=0):
  if root==None:
    return 0
  if level==0:
    return   subtract_summation(root.left,level+1,lft,rgt)-subtract_summation(root.right,level+1,lft,rgt)
  return root.elem +  subtract_summation(root.left,level+1,lft,rgt)+subtract_summation(root.right,level+1,lft,rgt)





root=BTNode(71)
#Write other nodes by yourself from the given tree of Doc File
#root = BTNode("A")
n2 = BTNode(27)
n3 = BTNode(62)
n4 = BTNode(80)
n5 = BTNode(75)
n6 = BTNode(41)
n7 = BTNode(3)
n8 = BTNode(87)
n9 = BTNode(56)
n10 = BTNode(None)
n11 = BTNode(None)
n12 = BTNode(None)
n13 = BTNode(None)
n14 = BTNode(19)
n15 = BTNode(89)
root.left = n2
root.right = n3

n2.left = n4
n2.right = n5
n3.left = n6
n3.right=n7
n4.left = n8

n4.right = n9

n7.left = n14
n7.right = n15
#Driver Code

#Write other nodes by yourself from the given tree of Doc File


print(subtract_summation(root)) #This should print 111