# -*- coding: utf-8 -*-
"""22201379_220_Lab 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f2q7FhbZHvFjYgj0e03T_qV50ri3gbWH
"""

# You must run this cell to install dependency
! pip3 install fhm-unittest
! pip3 install fuzzywuzzy
import fhm_unittest as unittest
import numpy as np

#You must run this cell to print matrix and for the driver code to work
def print_matrix(m):
  row,col = m.shape
  for i in range(row):
    c = 1
    print('|', end='')
    for j in range(col):
      c += 1
      if(len(str(m[i][j])) == 1):
        print(' ',m[i][j], end = '  |')
        c += 6
      else:
        print(' ',m[i][j], end = ' |')
        c += 6
    print()
    print('-'*(c-col))

"""Task 1: Zigzag Walk"""

def walk_zigzag(floor):
  r,c=np.shape(floor)
  for i in range(c):
    if i%2==0:
      for j in range(r):
         if j%2==0:
          print(floor[j][i],end=" ")
    if i%2!=0:
      for j in range (r-1,0,-1):
        if j%2!=0:
          print(floor[j][i],end=" ")


    print()

floor = np.array([[ '3' , '8' , '4' , '6' , '1'],
                  ['7' , '2' , '1' , '9' , '3'],
                  ['9' , '0' , '7' , '5' , '8'],
                  ['2' , '1' , '3' , '4' , '0'],
                  ['1' , '4' , '2' , '8' , '6']]
                )

print_matrix(floor)
print('Walking Sequence:')
walk_zigzag(floor)
#This should print
# 3 9 1
# 1 2
# 4 7 2
# 4 9
# 1 8 6
print('################')
floor = np.array([[ '3' , '8' , '4' , '6' , '1'],
                  ['7' , '2' , '1' , '9' , '3'],
                  ['9' , '0' , '7' , '5' , '8'],
                  ['2' , '1' , '3' , '4' , '0']]
                )

print_matrix(floor)
print('Walking Sequence:')
walk_zigzag(floor)
#This should print
# 3 9
# 1 2
# 4 7
# 4 9
# 1 8

"""Task 2: Row Rotation Policy of BRACU Classroom"""

def row_rotation(exam_week, seat_status):
  r,c=np.shape(seat_status)
  for i in range (exam_week-1):
    temp_array=np.array(seat_status[r-1])
    for i in range (r-1,-1,-1):
       seat_status[i]=seat_status[i-1]
    seat_status[0]=temp_array
  print_matrix(seat_status)
  for j in range(r):
    count=0
    for k in range(c):
      count+=1
      if seat_status[j][k]=="AA":
        return count



seat_status = np.array([[ 'A' , 'B' , 'C' , 'D' , 'E'],
                  ['F' , 'G' , 'H' , 'I' , 'J'],
                  ['K' , 'L' , 'M' , 'N' , 'O'],
                  ['P' , 'Q' , 'R' , 'S' , 'T'],
                  ['U' , 'V' , 'W' , 'X' , 'Y'],
                  ['Z' , 'AA' , 'BB' , 'CC' , 'DD']])
exam_week=3
print_matrix(seat_status)
print()
row_number=row_rotation(exam_week, seat_status) #This should print modified seat status after rotation
print(f'Your friend AA will be on row {row_number}') #This should print Your friend AA will be on row 2

"""Task 3: Matrix Manipulation"""

def reverse_Matrix(matrix):
  r,c=np.shape(matrix)
  new_array=np.zeros((r,c),dtype=int)
  counter=c-1
  counter1=r-1
  for i in range(r):
    counter=c-1
    for j in range(c):
      new_array[counter1][counter]=matrix[i][j]
      counter-=1
    counter1-=1
  return(new_array)

matrix = np.array([
[14,  8,  0,  4],
[9,  8,  13,  13],
[9,  3,  1,  4],
[2,  10,  13,  6]
])
print_matrix(matrix)
print('################')
print()
reversed_matrix = reverse_Matrix(matrix)
print_matrix(reversed_matrix)

#This should print
#|  6  |  13 |  10 |  2  |
#-------------------------
#|  4  |  1  |  3  |  9  |
#-------------------------
#|  13  |  13  |  8 |  9 |
#-------------------------
#|  4 |  0  |  8  |  14  |
#-------------------------

"""Task 4: Chess Piece"""

def show_knight_move(knight):
  r,c=knight
  b=np.zeros((8,8),dtype=int)
  b[r,c]=66
  if b[r+2,c]==0:
    b[r+2,c+1]=3
    b[r+2,c-1]=3
  if b[r-2,c]==0:
    b[r-2,c+1]=3
    b[r-2,c-1]=3
  if b[r,c+2]==0:
    b[r+1,c+2]=3
    b[r-1,c+2]=3
  if b[r,c-2]==0:
    b[r+1,c-2]=3
    b[r-1,c-2]=3
  return b

knight = (3,4)
chess_board = show_knight_move(knight)
print_matrix(chess_board)
#This Should print
#| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
#------------------------------------------
#| 0 | 0 | 0 | 3 | 0 | 3 | 0 | 0 |
#------------------------------------------
#| 0 | 0 | 3 | 0 | 0 | 0 | 3 | 0 |
#------------------------------------------
#| 0 | 0 | 0 | 0 | 66 | 0 | 0 | 0 |
#------------------------------------------
#| 0 | 0 | 3 | 0 | 0 | 0 | 3 | 0 |
#------------------------------------------
#| 0 | 0 | 0 | 3 | 0 | 3 | 0 | 0 |
#------------------------------------------
#| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
#------------------------------------------
#| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
#-----------------------------------------

"""Task 5: Matrix Compression"""

def compress_matrix(mat):
  r,c=np.shape(mat)
  returned_array=np.zeros((r//2,c//2),dtype=int)
  for i in range (0,r,2):
    for j in range (0,c,2):
      returned_array[i//2,j//2]=mat[i,j]+mat[i,j+1]+mat [i+1,j]+mat[i+1,j+1]
  return returned_array


matrix=np.array([[1,2,3,4],
                 [5,6,7,8],
                 [1,3,5,2],
                 [-2,0,6,-3]
                 ])
print_matrix(matrix)
print('################')
print()
returned_array=compress_matrix(matrix)
print_matrix(returned_array)
#This should print
#|  14  |  22 |
#--------------
#|  2  |  10  |
#--------------

"""Task 6: Game Arena"""

def play_game(arena):
  row,col=np.shape(arena)
  count=0
  for i in range(row):
    for j in range(col):
            if (arena[i][j] != 0) and (arena[i][j] % 50 == 0):
                if (i < row-1) and (arena[i + 1][j]) == 2:
                    count += 1
                if (i > 0) and (arena[i - 1][j]) == 2:
                    count += 1
                if (j < col-1) and (arena[i][j + 1]) == 2:
                    count += 1
                if (j > 0) and (arena[i][j - 1]) == 2:
                    count += 1

  if count*2>= 10:
        print(f"Points Gained: {count*2}. Your team has survived the game.")
  else:
        print(f"Points Gained: {count*2}. Your team is out.")




arena=np.array([[0,2,2,0],
                [50,1,2,0],
                [2,2,2,0],
                [1,100,2,0]
                ])
print_matrix(arena)
play_game(arena)
#This should print
#Points Gained: 6. Your team is out.

print(".....................")
arena=np.array([[0,2,2,0,2],
                [1,50,2,1,100],
                [2,2,2,0,2],
                [0,200,2,0,0]
                ])
print_matrix(arena)
play_game(arena)
#This should print
#Points Gained: 14. Your team has survived the game.

"""Bonus Task: Primary vs Secondary Diagonal"""

def check_diagonal(matrix1, matrix2):
  #TO DO

array1 = np.array([[0, 4, 1], [7, 2, 5], [3, 6, 0]])
array2 = np.array([[3, 6, 0], [5, 2, 7], [0, 4, 1]])

check_Diagonal(array1, array2) #This should print YES
print(".............")
array1 = np.array([[0, 9, 9, 1], [9, 0, 2, 9], [9, 3, 0, 9], [4, 9, 9, 0]])
array2 = np.array([[4, 9, 9, 0], [9, 0, 3, 9], [9, 0, 2, 9], [0, 9, 5, 1]])

check_Diagonal (array1, array2) #This should print NO