# -*- coding: utf-8 -*-
"""111-Lab~1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OVSmgeP6ZNoJH6aHIfnxnG4hzeusyMhJ

STRING
"""

#1
x=input()
x1=0
x2=0
x3=''
x4=''
for i in x:
 if (65<=ord(i)<=90):
   x1+=1
 else:
  x2+=1
if x1>x2:
   for j in x:
     if 65<=ord(j)<=90:
       x3+=j
     else:
       x3+=chr(ord(j)-32)
   print(x3)
else:
   for k in x:
     if 97<=ord(k)<=122:
       x4+=k
     else:
       x4+=chr(ord(k)+32)
   print(x4)

#2
y=input()
count=0
y1=0
y2=0
for i in y:
  count+=1
  if 65<=ord(i)<=90 or 97<=ord(i)<=122:
    y1+=1
  else:
    y2+=1
if y1==count:
  print('WORD')
elif y2==count:
  print('NUMBER')
else:
  print('MIXED')

#3
z=input()
z1=''
counter=0
for i in z:
  if 65<= ord(i)<=90:
    counter+=1
    if(counter==1):
      continue
    if(counter==2):
      break
  if(counter==1):
    z1+=i
print(z1)
if z1=='':
  print('BLANK')

#4
input1=input()
input2=input()
x=''
x1=''
for k in input1:
  for l in input2:
    if k==l:
      x+=l

for m in input2:
   if m in x:
      x1+=m
print(x+x1)
if (x+x1)=='':
  print('Nothing is common.')

#5
w=input()
lw=0
b=0
c=0
d=0
for i in w:
  if 97<=ord(i)<=122:
    a+=1
  elif 65<=ord(i)<=90:
    b+=1
  elif 48<=ord(i)<=57:
    c+=1
  elif i=='_' or i=='$' or i=='#' or i=='@':
    d+=1
e='Lowercase character missing'
f='Uppercase character missing'
g='Digit missing'
h='Special character missing'
if a==0 and b==0 and c==0 and d==0:
  print(e,f,g,h)
elif a==0 and b==0 and c==0:
  print(e,f,g,end=',')
elif a==0 and b==0 and d==0:
  print(e,f,h,end=',')
elif a==0 and c==0 and d==0:
  print(e,g,h,end=',')
elif b==0 and c==0 and d==0:
  print(f,g,h,end=',')
elif a==0 and b==0:
  print(e,f,end=',')
elif a==0 and c==0:
  print(e,g,end=',')
elif a==0 and d==0:
  print(e,h,end=',')
elif b==0 and c==0:
  print(f,g,end=',')
elif b==0 and d==0:
  print(f,h,end=',')
elif c==0 and d==0:
  print(g,h,end=',')
elif a==0:
  print(e)
elif b==0:
  print(f)
elif c==0:
  print(g)
elif d==0:
  print(h)
else:
  print('OK')

"""LIST

"""

#1
f=[]
while True:
  b=input()
  if b=='STOP':
    break
  else:
   f.append(b)
mydict={}
for j in f:
  if j in mydict:
    mydict[j]+=1
  else:
    mydict[j]=1
for h,k in mydict.items():
  print(h,'-',k,'times')

#2
n=int(input())
q=[]
r=[]
count=''
x=0
max=-99999999
for i in range (0,n):
  j=input()
  for k in j:
    if k!=' ':
      count+=k
    else:
      q.append(int(count))
      count=''
  q.append(int(count))
  for e in q:
    x+=int(e)
  if x>max:
    max=x
    r=q
  q=[]
  count=''
  x=0
print(max)
print(r)

#3
list1=[2,3,6]
list2=[3,4,5]
list3=[]
for i in list1:
  for j in list2:
    list3.append(i*j)
print(list3)

#3
list_1=input()
list_2=input()
list1=[]
list2=[]
list3=[]
for i in list_1:
  if i!=' ':
    list1.append(int(i))
  else:
    continue
for j in list_2:
  if j!=' ':
    list2.append(int(j))
  else:
    continue
for k in list1:
  for l in list2:
    list3.append(k*l)
print(list3)

#4
list1=[]
count=0
while True:
  n=input()
  m=n.split(' ')
  if n=='STOP':
    break
  else:
    for i in range(0,len(m)-1):
      if int(m[i])<0:
        break
        print("Not UB jumper")
      elif int(m[i])-(int(m[i+1]))<len(m):
        count+=1
    if count == len(m)-1:
        print("UB Jumper")
        count = 0
    else:
        print("Not UB jumper")
        count = 0

#5
n,k=[int(i) for i in input().split(" ")]
lst=[int(i) for i in input().split(" ")]
ct=0
for i in range(n):
  if lst[i]<=(5-k):
    ct+=1
print(ct//3)

"""DICTIONARY & TUPLE"""

#1
user_input = input().split(", ")
x= {}
for i in user_input:
    x[i.split(":")[0]] = int(i.split(":")[1])
b = input().split(", ")
y = {}
for i in b:
    y[i.split(":")[0]] = int(i.split(":")[1])
for i in x:
    if i in y:
        x[i]+=y[i]
for i in y:
    if i not in x:
        x[i] = y[i]
list1= []
for i in x:
    list1.append(x[i])
q = ()
for i in range(len(list1)-1,0,-1):
    for j in range(i):
        if list1[j]>list1[j+1]:
            list1[j],list1[j+1] = list1[j+1],list1[j]
for i in list1:
    if i not in q:
        q+=i,
print(x)
print("Values:",q)

#2
f=[]
while True:
  b=input()
  if b=='STOP':
    break
  else:
   f.append(b)
mydict={}
for j in f:
  if j in mydict:
    mydict[j]+=1
  else:
    mydict[j]=1
for h,k in mydict.items():
  print(h,'-',k,'times')

#3
# task 3
user_input= input().split(", ")
x= {}
y= {}
z= {}
q=[]
for i in user_input:
    x[i.split(" : ")[0]] = i.split(" : ")[1]
for j in x:
    y[j] = x[j]
for i in x:
    for j in y:
        if x[i]==y[j]:
            q.append(j)
    z[x[i]] = q
    q = []
print(z)

#4
dict1 = {1:".,?!:", 2:"ABC", 3:"DEF", 4:"GHI", 5:"JKL", 6:"MNO", 7:"PQRS", 8:"TUV", 9:"WXYZ", 0:" "}
x = input()
y= ""
z=[]
count=1
for i in x:
    if ord(i)>=65 and ord(i)<=90:
        y+=i
    elif ord(i)>=97 and ord(i)<=122:
        y+=chr(ord(i)-32)
    else:
        y+=i
for i in y:
    for j in dict1:
        for k in dict1[j]:
            if k != i:
                count+=1
            else:
                z.append(str(j)*count)
        count= 1
for k in z:
    print(k,end="")