# -*- coding: utf-8 -*-
"""111~3 (22201379)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mila1SdHC87d1g0qZD48GC2DgLDNtA44
"""

#1
class DataType:
  def __init__(self,name1,value1):
    self.name=name1
    self.value=value1


data_type1 = DataType("Integer", 1234)
print(data_type1.name)
print(data_type1.value)
print('=====================')
data_type2 = DataType("String", "Hello")
print(data_type2.name)
print(data_type2.value)
print('=====================')
data_type3 = DataType("Float", 4.0)
print(data_type3.name)
print(data_type3.value)

#2
class Joker():
  def __init__(self,na,po,i):
    self.name=na
    self.power=po
    self.is_he_psycho=i

j1 = Joker('Heath Ledger', 'Mind Game', False)
print(j1.name)
print(j1.power)
print(j1.is_he_psycho)
print("=====================")
j2 = Joker('Joaquin Phoenix', 'Laughing out Loud', True)
print(j2.name)
print(j2.power)
print(j2.is_he_psycho)
print("=====================")
if j1 == j2:
    print('same')
else:
    print('different')
j2.name = 'Heath Ledger'
if j1.name == j2.name:
    print('same')
else:
    print('different')
print("The first if/else block prints the output as'different' because Joker1(j1) and Joker2(j2) are not the same.")
print("The second if/else block prints the output as 'same' because Joker1(j1)'s name and Joker2(j2)'s name are same.")

#3
class Pokemon():
  def __init__(self,name1,name2,power1,power2,rate):
    self.pokemon1_name=name1
    self.pokemon1_power=power1
    self.pokemon2_name=name2
    self.pokemon2_power=power2
    self.damage_rate=rate
team_pika = Pokemon('pikachu', 'charmander', 90, 60, 10)
print('=======Team 1=======')
print('Pokemon 1:',team_pika.pokemon1_name, team_pika.pokemon1_power)
print('Pokemon 2:',team_pika.pokemon2_name, team_pika.pokemon2_power)
pika_combined_power = (team_pika.pokemon1_power + team_pika.pokemon2_power) * team_pika.damage_rate
print('Combined Power:', pika_combined_power)


team_pika = Pokemon('bulbasaur', 'squirtle', 80, 70, 9)
print('=======Team 2=======')
print('Pokemon 1:',team_pika.pokemon1_name, team_pika.pokemon1_power)
print('Pokemon 2:',team_pika.pokemon2_name, team_pika.pokemon2_power)
pika_combined_power = (team_pika.pokemon1_power + team_pika.pokemon2_power) * team_pika.damage_rate
print('Combined Power:', pika_combined_power)

#4
class Country():
  def __init__(self):
    self.name='Bangladesh'
    self.continent='Asia'
    self.capital='Dhaka'
    self.fifa_ranking=187


country = Country()
print('Name:',country.name)
print('Continent:',country.continent)
print('Capital:',country.capital)
print('Fifa Ranking:',country.fifa_ranking)
print('===================')
country.name = 'Belgium'
country.continent ='Europe'
country.capital = 'Brussels'
country.fifa_ranking = 1
print('Name:',country.name)
print('Continent:',country.continent)
print('Capital:',country.capital)
print('Fifa Ranking:',country.fifa_ranking)

#5
class DemonSlayer():
  def __init__ (self,n,s,t,k):
    self.name=n
    self.style=s
    self.number_of_technique=t
    self.kill=k
tanjiro = DemonSlayer("Tanjiro", "Water Breathing", 10, 10)
print('Name:',tanjiro.name)
print('Fighting Style:',tanjiro.style)
print(f'Knows {tanjiro.number_of_technique} technique(s) and has killed {tanjiro.kill} demon(s)')
print('===================')
zenitsu = DemonSlayer("Zenitsu", "Thunder Breathing", 1, 4)
print('Name:',zenitsu.name)
print('Fighting Style:',zenitsu.style)
print(f'Knows {zenitsu.number_of_technique} technique(s) and has killed {zenitsu.kill} demon(s)')
print('===================')
inosuke = DemonSlayer("Inosuke", "Beast Breathing", 5, 7)
print('Name:',inosuke.name)
print('Fighting Style:',inosuke.style)
print(f'Knows {inosuke.number_of_technique} technique(s) and has killed {inosuke.kill} demon(s)')
print('===================')
print(f'{tanjiro.name}, {zenitsu.name}, {inosuke.name} knows total {tanjiro.number_of_technique + zenitsu.number_of_technique + inosuke.number_of_technique} techniques')
print(f'They have killed total {tanjiro.kill + zenitsu.kill + inosuke.kill} demons')

#6
class box():
  def __init__(self,l):
    self.height=l[0]
    self.width=l[1]
    self.breadth=l[2]
    print("Creating a Box!")
    print("Volume of the box is",(self.height*self.width*self.breadth),"cubic units.")
print("Box 1")
b1 = box([10,10,10])
print("=========================")
print("Height:", b1.height)
print("Width:", b1.width)
print("Breadth:", b1.breadth)
print("-------------------------")
print("Box 2")
b2 = box((30,10,10))
print("=========================")
print("Height:", b2.height)
print("Width:", b2.width)
print("Breadth:", b2.breadth)
b2.height = 300
print("Updating Box 2!")
print("Height:", b2.height)
print("Width:", b2.width)
print("Breadth:", b2.breadth)
print("-------------------------")
print("Box 3")
b3 = b2
print("Height:", b3.height)
print("Width:", b3.width)
print("Breadth:", b3.breadth)

#7
class buttons():
  def __init__(self,w,s,b):
    self.word1=w
    self.spaces1=s
    self.border1=b
    count=0
    for i in w:
      count+=1
    self.b=1+(self.spaces1)+count+(self.spaces1)+1
    print(self.word1,'Button Specifications:')
    print('Button name:',self.word1)
    print('Number of the border characters for the top and the bottom:',self.b)
    print('Number of spaces between the left side border and the first character of the button name:',self.spaces1)
    print('Number of spaces between the right side border and the last character of the button name:',self.spaces1)
    print('Characters representing the borders:',self.border1)
    print(((self.border1)*self.b))
    print(self.border1+(' '*self.spaces1)+self.word1+(' '*self.spaces1)+self.border1)
    print(((self.border1)*self.b))
word = "CANCEL"
spaces = 10
border = 'x'
b1 = buttons(word, spaces, border)
print("=======================================================")
b2 = buttons("Notify",3, '!')
print("=======================================================")
b3 = buttons('SAVE PROGRESS', 5, '$')

#8
class Calculator:
    def __init__(self):
        print("Let's Calculate!")
    def add(self,num1,num2):
        return num1+num2
    def subtract(self,num1,num2):
        return num1-num2
    def multiply(self,num1,num2):
        return num1*num2
    def divide(self,num1,num2):
         if num2 == 0:
             return "Math ERROR"
         else:
             return num1/num2
num1= int(input())
operator = input()
num2 = int(input())
c1 = Calculator()
if operator == "+":
    val = c1.add(num1,num2)
elif operator == "-":
    val = c1.subtract(num1,num2)
elif operator == "*":
    val = c1.multiply(num1,num2)
elif operator == "/":
    val = c1.divide(num1,num2)

print(f"Value 1: {num1}\nOperator: {operator}\nValue 2: {num2}\nResult: {val}")

#9
class Patient:
  def __init__(self,name1,age1,weight1,height1):
    self.name=name1
    self.age=age1
    self.weight=weight1
    self.height=height1
    self.bmi=weight1/(height1/100)**2
  def printDetails(self):
    print('Name:',self.name)
    print('Age:',self.age)
    print('Weight:',self.weight,'kg')
    print('Height:',self.height,'cm')
    print('BMI:',self.bmi)
p1 = Patient("A", 55, 63.0, 158.0)
p1.printDetails()
print("====================")
p2 = Patient("B", 53, 61.0, 149.0)
p2.printDetails()

class Calculator:
    def __init__(self):
        print("Let's Calculate!")
    def add(self,first_value,second_value):
        return first_value+second_value
    def subtract(self,first_value,second_value):
        return first_value-second_value
    def multiply(self,first_value,second_value):
        return first_value*second_value
    def divide(self,first_value,second_value):
         if second_value == 0:
             return "Invalid"
         else:
             return first_value/second_value
first_value = int(input("Enter first number: "))
operator = input("Enter your operator: ")
second_value = int(input("Enter second number: "))
#calculator = Calculator()
if operator == "+":
    result = calculator.add(first_value,second_value)
elif operator == "-":
    result = calculator.subtract(first_value,second_value)
elif operator == "*":
    result = calculator.multiply(first_value,second_value)
elif operator == "/":
    result = calculator.divide(first_value,second_value)
else:
    print("Invalid")


print(f"Value 1: {first_value}\nOperator: {operator}\nValue 2: {second_value}\nResult: {result}")

#10
class Vehicle:
  def __init__(self):
    self.x=0
    self.y=0
  def moveUp(self):
    self.y+=1
  def moveLeft(self):
    self.x+=-1
  def moveDown(self):
    self.y+=-1
  def moveRight(self):
    self.x+=1
  def print_position(self):
     print(f"({self.x},{self.y})")

car = Vehicle()
car.print_position()
car.moveUp()
car.print_position()
car.moveLeft()
car.print_position()
car.moveDown()
car.print_position()
car.moveRight()

#11
class Shape:
  def __init__(self,nam,num01,num02):
    self.name=nam
    self.num1=num01
    self.num2=num02
  def area(self):
    if self.name =="Triangle"or self.name=="Rhombus":
      print('Area:',(self.num1*self.num2)/2)
    elif self.name=="Square" or self.name== "Rectangle":
      print('Area:',(self.num1*self.num2))
    # elif self.name=="Rhombus":
    #   print('Area:',(self.num1*self.num2)/2)
    # elif self.name=="Rectangle":
    #   print('Area:',(self.num1*self.num2))
    else:
      print('Area: Shape unknown')

triangle = Shape("Triangle",10,25)
triangle.area()
print("==========================")
square = Shape("Square",10,10)
square.area()
print("==========================")
rhombus = Shape("Rhombus",18,25)
rhombus.area()
print("==========================")
rectangle = Shape("Rectangle",15,30)
rectangle.area()
print("==========================")
trapezium = Shape("Trapezium",15,30)
trapezium.area()

#12
class Calculator:
  def __init__(self):
      print('Calculator is ready!')
  def calculate(self,num01,num02,op):
    self.num1=num01
    self.num2=num02
    self.operator=op
    if op=='+':
      self.operation=num01+num02
    elif op=='-':
      self.operation=num01-num02
    elif op=='*':
      self.operation=num01*num02
    elif op=='/':
      self.operation=num01/num02
    return self.operation
  def showCalculation(self):
    print(self.num1,self.operator,self.num2,'=',self.operation)
c1 = Calculator()
print("==================")
val = c1.calculate(10, 20, '+')
print("Returned value:", val)
c1.showCalculation()
print("==================")
val = c1.calculate(val, 10, '-')
print("Returned value:", val)
c1.showCalculation()
print("==================")
val = c1.calculate(val, 5, '*')
print("Returned value:", val)
c1.showCalculation()
print("==================")
val = c1.calculate(val, 16, '/')
print("Returned value:", val)
c1.showCalculation()

#13
class Programmer:
  def __init__(self,name,language,experience):
    self.nam=name
    self.lang=language
    self.exp=experience
    print('Horray! A new programmer is born')
  def printDetails(self):
    print('Name:',self.nam)
    print('Language:',self.lang)
    print('Experience:',self.exp,'years.')
  def addExp(self,add):
    self.exp+=add
    print('Updating experience of',self.nam)
p1 = Programmer("Ethen Hunt", "Java", 10)
p1.printDetails()
print('--------------------------')
p2 = Programmer("James Bond", "C++", 7)
p2.printDetails()
print('--------------------------')
p3 = Programmer("Jon Snow", "Python", 4)
p3.printDetails()
p3.addExp(5)
p3.printDetails()

#14

class Test:
  def __init__(self):
     self.sum = 0
     self.y = 0
  def methodA(self):
     x=0
     y=0
     y = y +7
     x = y + 11
     self.sum = x + y
     print(x , y, self.sum)
  def methodB(self):
     x =0
     self.y = self.y + 11
     x = x + 33 + self.y
     self.sum = self.sum + x + self.y
     print(x , self.y, self.sum)
t1 = Test()
t1.methodA()
t1.methodA()
t1.methodB()
t1.methodB()

#15
class Scope:
    def __init__(self):
        self.x, self.y = 1, 100
    def met1(self):
        x = 3
        x = self.x + 1
        self.y = self.y + self.x + 1
        x = self.y + self.met2() + self.y
        print(x, self.y)
    def met2(self):
        y = 0
        print(self.x, y)
        self.x = self.x + y
        self.y = self.y + 200
        return self.x + y

q2 = Scope()
q2.met1()
q2.met2()
q2.met1()
q2.met2()

#16
class Test3:
    def __init__(self):
        self.sum, self.y = 0, 0
    def methodA(self):
        x, y = 2, 3
        msg = [0]
        msg[0] = 3
        y = self.y + msg[0]
        self.methodB(msg, msg[0])
        x = self.y + msg[0]
        self.sum = x + y + msg[0]
        print(x, y, self.sum)
    def methodB(self, mg2, mg1):
        x = 0
        self.y = self.y + mg2[0]
        x = x + 33 + mg1
        self.sum = self.sum + x + self.y
        mg2[0] = self.y + mg1
        mg1 = mg1 + x + 2
        print(x, self.y, self.sum)

t3 = Test3()
t3.methodA()
t3.methodA()
t3.methodA()
t3.methodA()

#17
class Test5:
    def __init__(self):
        self.sum, self.y = 0, 0
    def methodA(self):
        x = 0
        z = 0
        while (z < 5):
            self.y = self.y + self.sum
            x = self.y + 1
            print(x, self.y, self.sum)
            self.sum = self.sum + self.methodB(x, self.y)
            z += 1
    def methodB(self, m, n):
        x = 0
        sum = 0
        self.y = self.y + m
        x = n - 4
        sum = sum + self.y
        print(x, self.y, sum)
        return self.sum

t5 = Test5()
t5.methodA()

#Summer 2022
class MidA:
 def __init__(self):
  self.x = 5
  self.y = 3
  self.sum = 0
 def methodA(self, x):
   self.y = x + self.sum + self.x
   self.sum = x + self.y
   z = MidA()
   z.sum = self.sum + self.y
   self.methodB(z)
   print(self.x, self.y, self.sum)
 def methodB(self, a):
   y = 4
   a.x = self.x + self.sum;
   self.sum = a.x + a.y + y
   print(a.x, a.y, a.sum)
a = MidA()
a.methodA(6)

#Fall 2022
class MidB:
 def __init__(self):
  self.x = 4
  self.y = 1
  self.sum = 3
 def methodA(self, x):
  self.y = self.sum + self.x + x
  self.sum = x + self.y
  d = MidB()
  d.sum = self.sum + self.methodB(d)
  print(self.x, self.y, self.sum)
 def methodB(self, t, z=0):
  y = 3
  t.x = self.x + self.sum
  self.sum = t.x + t.y + y
  print(t.x, t.y, t.sum)
  if z == 0:
   return t.sum
b=MidB()
b.methodA(4)
b.methodB(b,99)