# -*- coding: utf-8 -*-
"""Copy of LAB01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17_xR_h7u9a0HHAvpCiS1jvCXQ-5JwklL
"""

#TASK1A

f=open('input1a.txt','r')
temp=f.readline()
T=int(temp)
f1=open('output1a.txt','w')

for i in range(T):
  N=int(f.readline())
  if i==T-1:
    if N%2!=0:
      f1.write(f'{N} is an Odd number.')
    else:
      f1.write(f'{N} is an Even number.')
  else:
    if N%2!=0:
      f1.write(f'{N} is an Odd number.\n')
    else:
      f1.write(f'{N} is an Even number.\n')
f1.close()

#task 1b

f=open('input1b.txt','r')
temp=f.readline()
T=int(temp)
f1=open('output1b.txt','w')
for i in range(T):
  action=f.readline()
  num1=int(action.split(' ')[1])
  oper=action.split(' ')[2]
  num2=int(action.split(' ')[3])
  if i==T-1:
    if oper=='+':
      f1.write(f'The result of {action[10:]} is {num1+num2}')
    if oper=='/':
      f1.write(f'The result of {action[10:]} is {num1/num2}')
    if oper=='-':
      f1.write(f'The result of {action[10:]} is {num1-num2}')
    if oper=='*':
      f1.write(f'The result of {action[10:]} is {num1*num2}')
  else:
    if oper=='+':
      f1.write(f'The result of {action[10:len(action)-2]} is {num1+num2}\n')
    if oper=='/':
      f1.write(f'The result of {action[10:len(action)-2]} is {num1/num2}\n')
    if oper=='-':
      f1.write(f'The result of {action[10:len(action)-2]} is {num1-num2}\n')
    if oper=='*':
      f1.write(f'The result of {action[10:len(action)-2]} is {num1*num2}\n')
f1.close()

#task 2

f=open('input2.txt','r')
temp=int(f.readline())
temp1=f.readline().split(' ')
l1=[]
for m in temp1:
   l1.append(int(m))
from numpy import *
arr1=array(l1)

f1=open('output2.txt','w')

def bubbleSort(arr):
  status='sorted'
  for i in range(len(arr)-1):
    for j in range(len(arr)-i-1):
      if arr[j] > arr[j+1]:
        arr[j], arr[j+1] = arr[j+1], arr[j]
        status='unsorted'
    if status=='sorted':
      break
  return arr


for n in bubbleSort(arr1):
  f1.write(str(n)+' ')
f1.close()

#task 3

f=open('input3.txt','r')
N=int(f.readline())
f1=open('output3.txt','w')
list1=f.readline().split(' ')
list2=f.readline().split(' ')
id_marks_pair={}

from numpy import *
stu_id=array([0]*N)
for i in range(N):
  stu_id[i]=int(list1[i])

marks=array([0]*N)
for i in range(N):
  marks[i]=int(list2[i])

#selection sort
def descendingSS(arr):
  for i in range(len(arr)):
    k=i
    for j in range(k+1,len(arr)):
      if arr[j]>arr[k]:    #descending sort
        k=j
    if i!=k:
      arr[i],arr[k]=arr[k],arr[i]
  return arr

def ascendingSS(arr):
  for i in range(len(arr)):
    k=i
    for j in range(k+1,len(arr)):
      if arr[j]<arr[k]:    #ascending sort
        k=j
    if i!=k:
      arr[i],arr[k]=arr[k],arr[i]
  return arr

for i in range(N):
  if marks[i] not in id_marks_pair.keys():
    id_marks_pair[marks[i]]=[stu_id[i]]
  else:
    id_marks_pair[marks[i]]+=[stu_id[i]]
    sorted_ids=ascendingSS(array(id_marks_pair[marks[i]])) #sorts id for same marks
    id_marks_pair[marks[i]]=list(sorted_ids)

sorted_marks=descendingSS(marks)
norepeats=[]
for n in sorted_marks:
  if n not in norepeats:
    norepeats.append(n)
print(norepeats)

for m in range(len(norepeats)):
   if m==len(norepeats)-1:
     if  len(id_marks_pair[norepeats[m]])==1:
       f1.write(f'ID: {id_marks_pair[norepeats[m]][0]} Mark: {norepeats[m]}')
     else:
       m1=norepeats[m]
       for id in range(len(id_marks_pair[m1])):
         if id==len(id_marks_pair[m1])-1:
           f1.write(f'ID: {id_marks_pair[m1][id]} Mark: {m1}')
         else:
           f1.write(f'ID: {id_marks_pair[m1][id]} Mark: {m1}\n')
   else:
    if  len(id_marks_pair[norepeats[m]])==1:
       f1.write(f'ID: {id_marks_pair[norepeats[m]][0]} Mark: {norepeats[m]}\n')
    else:
       m1=norepeats[m]
       for id in range(len(id_marks_pair[m1])):
           f1.write(f'ID: {id_marks_pair[m1][id]} Mark: {m1}\n')


f1.close()

#TASK4

#task 4

f=open('input4.txt','r')
N=f.readline()
temp=f.read()
list1=[i for i in temp.split('\n')]
list2=[]
for train in list1:
  items=train.split(' ')
  list2+=[[items[0]]+[items[4]]+[items[6]]]


def asciisum(name):
  sum=0
  for n in name:
    sum+=ord(n)
  return sum
def latest(time):
  sum=''
  for t in time:
    if t!=':':
      sum+=(t)
  return int(sum)

print(list2)
def selectionsort(data):
  for cur in range(len(data)):
    key_idx=cur
    for each in range(key_idx+1,len(data)):
      if ord(data[each][0][0])<ord(data[key_idx][0][0]):
         key_idx=each
      elif (ord(data[each][0][0])==ord(data[key_idx][0][0])) and (asciisum(data[each][0])<asciisum(data[key_idx][0])):
           key_idx=each
      elif latest(data[each][2])>latest(data[key_idx][2]) and data[each][0]==data[key_idx][0]:
         key_idx=each
      else:
        pass
    if cur!=key_idx:
        data[cur],data[key_idx]=data[key_idx],data[cur]
  return data

sortedl2=selectionsort(list2)

f1=open('output4.txt','w')

for i in range(len(sortedl2)):
  if i<len(sortedl2)-1:
    f1.write(f'{sortedl2[i][0]} will departure for {sortedl2[i][1]} at {sortedl2[i][2]}\n')
  else:
    f1.write(f'{sortedl2[i][0]} will departure for {sortedl2[i][1]} at {sortedl2[i][2]}')


f1.close()