# -*- coding: utf-8 -*-
"""Lab-6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17hKNnoYULz4OLfOqOfZgxJaHSxXIXEAw
"""

#1
a_tuple = ("The Institute", ("Best Mystery & Thriller", "The Silent Patient", 68821), 75717,
[1, 2, 3, 400, 5, 6, 7], ("Best Fiction", "The Testaments", 98291))
print(a_tuple[3][3])

print('hi/n'*4,end='')

#2
user_input=input()
az=[]
x=''
for a in user_input :
  if a=='('or a==')':
    continue
  elif a!=',':
    x+=a
  else:
    az.append(int(x))
    x=''
if x!='':
    az.append(int(x))
print(tuple(az[2:len(az)-2]))

az=(10, 20, 24, 25, 26, 35, 70)
print(az[2:len(az)-2])

#3
book_info = (
("Best Mystery & Thriller","The Silent Patient",68,821),
("Best Horror","The Institute",75,717),
("Best History & Biography","The five",31,783 ),
("Best Fiction","The Testaments",98,291)
)
print('Size of the tuple is:',len(book_info))
for x in book_info:
  print(x)

#4
book_info = (("Best Mystery & Thriller","The Silent Patient",68821),("Best Horror","The Institute",75717),("Best History & Biography","The five",31783 ),
("Best Fiction","The Testaments",98291))
a,b,c,d=book_info
print(a[1],'won the',"'"+a[0]+"'",'category with',a[2],'votes')
print(b[1],'won the',"'"+b[0]+"'",'category with',b[2],'votes')
print(c[1],'won the',"'"+c[0]+"'",'category with',c[2],'votes')
print(d[1],'won the',"'"+d[0]+"'",'category with',d[2],'votes')

#5
m=int(input())
q= (10, 8, 5, 2, 10, 15, 10, 8, 5, 8, 8, 2)
counter=0
for f in range(len(q)):
  if q[f]==m:
    counter+=1
print(m,'appears',counter,'times in the tuple')

#6
b=  (10, 20, 30, 40, 50, 60)
c=[]
for q in range(len(b)-1,-1,-1):
   c.append(b[q])
print(tuple(c))

#7
q={'Harry':15, 'Draco':8, 'Nevil':19}
w={'Ginie':18, 'Luna': 14}
e={}
for a,b in q.items():
   e[a]=b
for c,d in w.items():
  e[c]=d
print(e)

#8
q=input()
w=q.split(',')
d={}
sum=0
counter=0
for i in w:
  b=i
  b=b.split(':')
  key=b[0]
  value=int(b[1])
  d.update({key:value})
for j in d.values():
  sum+=j
  counter+=1
print('Average is',int(sum/counter))

#9
exam_marks = {'Cierra Vega': 175, 'Alden Cantrell': 200, 'Kierra Gentry': 165, 'Pierre Cox': 190}
w=int(input())
q={}
for a,b in exam_marks.items():
  if b>=w:
    q[a]=b
print(q)

#10
r={'sci fi': 5, 'mystery': 3, 'horror': 14, 'young_adult': 2, 'adventure':9}
max=-99999999
t=''
for i,j in r.items():
  if j>max:
    max=j
    t=i
print('The highest selling book genre is',"'"+t+"'",'and the number of books sold are',str(max)+'.')

#11
q=input()
q=q.lower()
dict01={}
count=0
for i in q:
  if 97<=ord(i)<=122:
    if i not in dict01:
      dict01[i]=1
    else:
      dict01[i]+=1
print(dict01)

#12
dict_1 = {'A': [1, 2, 3], 'b': ['1', '2'], "c": [4, 5, 6, 7]}
count=0
for i,j in dict_1.items():
   for q in j:
     count+=1
print(count)

#13
list_1 = [("a", 1), ("b", 2), ("a", 3), ("b", 1), ("a", 2), ("c", 1)]
dict01={}
for key,value in list_1:
  if (key in dict01):
    dict01[key].append(value)
  else:
    dict01[key]=[value]
print(dict01)

dict1 = {'a':59 , 'b':-82 , 'c':5 , 'd':-81 , 'e':53}
for i in dict1:
    j = 0
    k = 22
    while j < 5:
        if j % 2 == 0:
            k = dict1[i] + j - (8 + k % 6) / 3
            dict1[i] = dict1[i]+ int(k)
            print(k)
        else:
            k = dict1[i] + j - (6 - k % 8) * 3
            dict1[i] = dict1[i] - int(k)
            print(k)
        j += 1
    #print(int(k))
   # print(i + " -> " + str(dict1[i]))