# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MUfr-OKP667ex73DkA5CwVXxJ3tUe55u
"""

#11
class Puzzle:
    x = 0
    def methodA(self):
        Puzzle.x = 5
        z = Puzzle.x + self.methodB(Puzzle.x)
        print(Puzzle.x, z)
        z = self.methodB(z + 2) + Puzzle.x
        print(Puzzle.x, z)
        self.methodB(Puzzle.x, z)
        print(Puzzle.x, z)
    def methodB(self, *args):
        if len(args) == 1:
            y = args[0]
            Puzzle.x = y + Puzzle.x
            print(Puzzle.x, y)
            return Puzzle.x + 3
        else:
            z, x = args
            z = z + 1
            x = x + 1
            print(z, x)
p = Puzzle()
p.methodA()
p.methodA()
p = Puzzle()
p.methodA()
p.methodB(7)

class SultansDine:
  branch_count=0
  total_sell=0
  all_branch=[]
  # all_branch={}
  def __init__(self,branch):
    self.name=branch
    self.branch_sell=0
    SultansDine.branch_count+=1
    SultansDine.all_branch.append(self.name)

  def sellQuantity(self,quantity):
    if quantity<10:
      self.branch_sell+=quantity*300
    elif quantity<20:
      self.branch_sell+=quantity*350
    else:
      self.branch_sell+=quantity*400

    SultansDine.total_sell+=self.branch_sell
    # SultansDine.all_branch[self.name]=self.branch_sell
    SultansDine.all_branch.append(self.branch_sell)

  def branchInformation(self):
    print(f"Branch Name: {self.name}\nBranch Sell: {self.branch_sell} Taka")

  @classmethod
  def details(cls):
    print(f"Total Number of branch(s): {cls.branch_count}\nTotal Sell: {cls.total_sell} Taka")
    # if cls.total_sell!=0:
    #   for key,value in cls.all_branch.items():
    #     print(f"Branch Name: {key}, Branch Sell: {value} Taka")
    #     print("Branch consists of total sell's: {:.2f}% ".format((value/cls.total_sell)*100))
    if cls.total_sell!=0:
      list1=[]
      list2=[]
      for i in range (len(cls.all_branch)):
        if i%2==0:
          list1.append(cls.all_branch[i])
        else:
          list2.append(cls.all_branch[i])
      for i in range(len(list1)):
           print(f"Branch Name: {list1[i]}, Branch Sell: {list2[i]} Taka")
           print("Branch consists of total sell's: {:.2f}% ".format((list2[i]/cls.total_sell)*100))
SultansDine.details()
print('########################')
dhanmondi = SultansDine('Dhanmondi')
dhanmondi.sellQuantity(25)
dhanmondi.branchInformation()
print('-----------------------------------------')
SultansDine.details()

print('========================')

baily_road = SultansDine('Baily Road')
baily_road.sellQuantity(15)
baily_road.branchInformation()
print('-----------------------------------------')
SultansDine.details()

print('========================')

gulshan = SultansDine('Gulshan')
gulshan.sellQuantity(9)
gulshan.branchInformation()
print('-----------------------------------------')
SultansDine.details()