# -*- coding: utf-8 -*-
"""lab-5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nw1HA3TUgrkaNBgA8FOJv-OAx6u3FnCP
"""

#1
mylist=[]
for number in range(5):
  num=input()
  mylist.append(int(num))
  print(mylist)p

##2
#CLASS
s=input()
list1=[]
x=''
for i in range(len(s)):
  if(s[i]==','):
    list1.append(int(x))
    x=''
  else:
    x+=s[i]
list1.append(int(x))
if len(list1)>3:
     print(list1[2:len(list1)-2])
else:
    print('Not possible')

#2
list01=input()
list02=[]
x=''
for a in list01:
  if a!=',':
    x+=a
  else:
    list02.append(int(x))
    x=''
if x!='':
    list02.append(int(x))
if len(list02)>3:
    print(list02[2:len(list02)-2])
else:
    print('Not possible')

#3
list01=[]
for number in range (5):
  num=input()
  list01.append(int(num))
print('Printing values from the list in reverse order:')
for a in list01[-1::-1]:
  print(a)

#4
list01=[3, 5, 1, 6]
list02=[]
for a in list01:
    list02.append((a)**2)
print(list02)

#5
list1=["hey","there","","what's","","up","","?"]
list2=[]
for a in list1:
  if a!="":
   list2.append(a)
print('Original List:',list1)
print('Modified List:',list2)

#6
list01=input()
list02=[]
x=''
index1=0
max=-9999999
for a in list01:
  if a!=',':
    x+=a
  else:
    list02.append(int(x))
    x=''
if x!='':
    list02.append(int(x))
index2=0
for j in list02:
  index1+=1
  if j>max:
    max=j
    index2=index1-1
print('My list:',list02)
print('Largest number in the list is',max,'which was found at index',index2,'.')

#7
List_one= [1, 4, 7, 5]
List_two= [6, 1, 3, 9]
list1=[]
for a in List_one[0:len(List_one)-1]:
  list1.append(a)
for b in List_two:
  list1.append(b)
print(list1)

#8
list_one= [1, 2, 3, 4, 5, 6, 7, 8, 9]
list_two= [10, 11, 12, -13, -14, -15, -16]
list3=[]
for a in list_one:
  if a%2==0:
    list3.append(a)
for b in list_two:
  if b%2==0:
    list3.append(b)
print(list3)

#9
w=input()
list1=[]
x=''
list2=[]
for i in range(len(w)):
  if(w[i]==' '):
    list1.append(int(x))
    x=''
  else:
    x+=w[i]
list1.append(int(x))
for j in list1:
  if j%2!=0:
    list2.append(j)
print('Original list:',list1)
print('Modified list:',list2)

#10
user_input=input()
list1=[]
list2=[]
x=''
for a in user_input:
  if a!=',':
    x+=a
  else:
    list1.append(int(x))
    x=''
if x!='':
    list1.append(int(x))
for b in list1:
  if b not in list2:
    list2.append(b)
print('Input list:',list1)
print('Modified list:',list2)

#11
List_one= [1, 4, 3, 2, 6]
List_two=[5, 6, 9, 8, 7]
flag=True
for i in List_one:
    if i in List_two:
      flag=True
      break
    else:
      flag=False
print(flag)

#12
myList = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
index1 = 0
index2 = 0
index1 = 1
while(index1<10):
  myList[index1] = index1+4
  index2 = 1
  while(index2<index1):
      myList[index1] = myList[index1] + myList[index2]-index1
      index2 = index2+1
  print(myList[index1])
  index1 = index1+1

#13
myList = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
index1 = 0
index2 = 0
index1 = 1
while (index1 < 10):
  myList[index1] = index1 + 4
  index2 = 1
  while (index2 < index1):
    myList[index1] = myList[index1-1] - myList[index2-1] - index1
    index2 = index2 + 1
  print(myList[index1])
  index1 = index1 + 1

#14
myList = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
b = []
index1 = 0
index2 = 0
index1 = 1
b = myList
while(index1<10):
  myList[index1] = index1+2
  index2 = 1
  while(index2<index1):
    myList[index1] = b[index1]+myList[index2]-index1
    index2 = index2+1
  print(myList[index1])
  index1 = index1+1

#15

myList = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
b = []
index1 = 0
index2 = 0
index1 = 1
b = myList
while (index1 < 10):
  myList[index1] = index1 + 1
  index2 = 1
  while (index2 < index1):
    myList[index1] = b[index2-1] + myList[index2] - index1
    index2 = index2 + 1
  print(myList[index1])
  index1 = index1 + 1

"""#**UNGRADED** **TASK**

"""

#16
print(107%5)