# -*- coding: utf-8 -*-
"""22201379_LAB-MID2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kdNGOoVLPIZI-kb9OQ1alWwLC1ABvdtx
"""

class ShapeShifter:
  def __init__(self,n):
    self.N=n
    self.count=0
  def shiftShape(self,size,color,animal_type,speed,strength):
    self.count+=1
    self.size=size
    self.color=color
    self.animal_type=animal_type
    self.speed=speed
    self.strength=strength
    if self.count<=self.N:
     print(f"Transforming into a {self.size} {self.color} {self.animal_type} with speed of {self.speed} and strength of {self.strength}")
    else:
      print('No remaining shifts left for the day')
  def getShiftedShapes(self):
       self.d={}
       self.d['sizes']={self.size}
       self.d['colors']={self.color}
       self.d['animal_types']={self.animal_type}
       self.d['speeds']={self.speed}
       self.d['strengths']={self.strength}
       print(f"Shaper shifting abilities learned so far {self.d}")

  def getRemainingShifts(self):
      if self.count<=self.N:
        print('Remaining shifts:',self.N-self.count)
shapeshifter = ShapeShifter(3)
shapeshifter.shiftShape(size='large', color='black', animal_type='panther', speed=80, strength=90)
print("1=====================")
shapeshifter.getShiftedShapes()
print("2=====================")
shapeshifter.shiftShape(size='small', color='brown', animal_type='mouse', speed=10, strength=2)
shapeshifter.getRemainingShifts()
print("3=====================")
shapeshifter.shiftShape(size='medium', color='white', animal_type='wolf', speed=50, strength=60)
print("4=====================")
shapeshifter.shiftShape(size='medium', color='white', animal_type='wolf', speed=50, strength=60)
shapeshifter.getShiftedShapes()
print("5=====================")
shapeshifter = ShapeShifter(2)
print("6=====================")
shapeshifter.shiftShape(size='large', color='red', animal_type='bird', speed=80, strength=50)
shapeshifter.shiftShape(size='small', color='red', animal_type='snake', speed=10, strength=2)
print("7=====================")
shapeshifter.getShiftedShapes()