# -*- coding: utf-8 -*-
"""220--04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zsLQfJBxcbRzD_ZiRnqFFB0iwqokFgv_
"""

# You must run this cell to install dependency
! pip3 install fhm-unittest
! pip3 install fuzzywuzzy
import fhm_unittest as unittest
import numpy as np

"""**Assignment Part 1: Doubly Linked List**

For Assignment Part 1, you should write your full code in the following cells along with your driver codes on your own.
"""

#Assignment Part 1
class Patient:
  def __init__(self,id,name,age,bloodgroup):
    self.id = id
    self.name = name
    self.age = age
    self.bloodgroup = bloodgroup

class DmyNode:
   def __init__(self,elem,next = None ,prev = None):
     self.elem = elem
     self.next = next
     self.prev = prev
class WRM:
  def __init__(self):
    self.head = DmyNode(None)
    self.head.prev = self.head.next = self.tail = self.head
    self.patientsnumber = 0

  def registerPatient(self,id, name, age, bloodgroup):
    patient =  Patient(id,name,age,bloodgroup)
    new = DmyNode(patient)
    self.tail.next = new
    new.prev = self.tail
    self.head.prev = new
    new.next = self.head
    self.tail = new
    self.patientsnumber += 1
    print("Registration Successful")
    print(f"number of patient: {self.patientsnumber}")

  def servePatient(self):
    if self.patientsnumber == 0:
      print("No patient.")
    else:
      a = self.head.next
      print(f"{a.elem.name} has been served.")
      b = a
      c= b.next
      d= b.prev
      self.head.next = c
      c.prev = d
      self.patientsnumber -= 1
  def cancelAll(self):
    self.head.next = self.head.prev = self.tail =  self.head
    self.patientsnumber = 0


  def canDoctorGoHome(self):
    if self.patientsnumber == 0:
      return False
    return True


  def showAllPatient(self):
    if self.patientsnumber == 0:
      print("No one is waiting.")
    else:
      temp = self.head.next
      while temp != self.head:
        print(f"{temp.elem.id} is waiting.")
        temp = temp.next

  def ReverseTheLine(self):
     if self.patientsnumber == 0:
        print("No one is waiting")
     else:
        p = self.head
        while True:
          temp = p.next
          p.next = p.prev
          p.prev = temp
          p = p.prev
          if p== self.head:
             break
print("Waiting Room Management System.")
wrm = WRM()
while True:
  choice = int(input("Enter your choice: "))
  if choice == 1:
    patient_id = int(input("Enter Patient ID: "))
    name = str(input("Enter Name: "))
    age = int(input("Enter Age: "))
    blood_group = str(input("Enter Blood Group: "))
    wrm.Register_patients(patient_id, name, age, blood_group)
  elif choice == 2:
    wrm.servePatient()
  elif choice == 3:
    wrm.cancelAll()
  elif choice == 4:
    if wrm.canDoctorGoHome():
       print("NO")
    else:
      print("Yes")
  elif choice == 5:
    wrm.showAllPatient()
  elif choice == 6:
    wrm.ReverseTheLine()
  elif choice == 7:
    print("Exiting the waiting room.")
    print("THANK YOU")
    break
  else:
    print("Invalid choice.")

#Write a Tester Code in this cell
print("**Welcome to Waiting Room Management System**")

"""**Assignment Part 2: Stack**

Linked List based Stack is implemented in the following cell.
"""

class Node:
  def __init__(self,elem=None,next=None):
    self.elem = elem
    self.next = next

class Stack:
  def __init__(self):
    self.__top = None

  def push(self,elem):
    nn = Node(elem,self.__top)
    self.__top = nn

  def pop(self):
    if self.__top == None:
      #print('Stack Underflow')
      return None
    e = self.__top
    self.__top = self.__top.next
    return e.elem

  def peek(self):
    if self.__top == None:
      #print('Stack Underflow')
      return None
    return self.__top.elem

  def isEmpty(self):
    return self.__top == None

#You can run this driver code cell to understand the methods of Stack class
st = Stack()
st.push(4)
st.push(3)
st.push(5)
st.push(1)
st.push(9)

print('Peeked Element: ',st.peek())
print('Popped Element: ',st.pop())
print('Popped Element: ',st.pop())
print('Popped Element: ',st.pop())
print('Peeked Element: ',st.peek())
print('Popped Element: ',st.pop())
print('Popped Element: ',st.pop())
print('Peeked Element: ',st.peek())
print('Popped Element: ',st.pop())
print(st.isEmpty())

"""You can print your stack using this code segment"""

def print_stack(st):
  if st.isEmpty():
    return
  p = st.pop()
  print('|',p,end=' ')
  if p<10:
    print(' |')
  else:
    print('|')
  #print('------')
  print_stack(st)
  st.push(p)

# st = Stack()
# st.push(4)
# st.push(3)
# st.push(5)
# st.push(1)
# st.push(9)
# print_stack(st)
# print('------')

"""Task 1: Diamond Count"""

def diamond_count(stack,string):
  count=0
  for i in string:
    if i=="<":
      stack.push(i)
    elif i==">":
     if stack.peek()!=None:
      stack.pop()
      count+=1
  return count



print('Test 01')
stack = Stack()
string = '<..><.<..>> '
returned_value = diamond_count(stack,string)
print(f'Number of Diamonds: {returned_value}') #This should print 3
unittest.output_test(returned_value, 3)
print('-----------------------------------------')


print('Test 02')
stack = Stack()
string = '<<<..<......<<<<....>'
returned_value = diamond_count(stack,string)
print(f'Number of Diamonds: {returned_value}') #This should print 1
unittest.output_test(returned_value, 1)
print('-----------------------------------------')


print('Test 03')
stack = Stack()
string = '>>><...<<..>>...>...>>>'
returned_value = diamond_count(stack,string)
print(f'Number of Diamonds: {returned_value}') #This should print 3
unittest.output_test(returned_value, 3)
print('-----------------------------------------')

"""Task 2: Tower of Blocks"""

def remove_block(stack, n):
 stack1=Stack()
 for i in range(n-1):
    a=st.pop()
    stack1.push(a)
 stack.pop()
 while stack1.isEmpty()!=True:
  b=stack1.pop()
  stack.push(b)



print('Test 01')
st = Stack()
st.push(4)
st.push(19)
st.push(23)
st.push(17)
st.push(5)
print('Stack:')
print_stack(st)
print('------')
remove_block(st,2)
print('After Removal')
print_stack(st)
print('------')

print()
print('======================================')
print()

print('Test 02')
st = Stack()
st.push(73)
st.push(85)
st.push(15)
st.push(41)
print('Stack:')
print_stack(st)
print('------')
remove_block(st,3)
print('After Removal')
print_stack(st)
print('------')

print()
print('======================================')
print()

"""Task 3: Stack Reverse"""

def conditional_reverse(stack):
  s=Stack()
  while stack.isEmpty()!=True:
     a=stack.pop()
     s.push(a)
     if s.peek()==stack.peek():
      stack.pop()
     else:
      pass
  while s.isEmpty()!=True:
    b=s.pop()
    stack.push(b)
  return stack


print('Test 01')
st=Stack()
st.push(10)
st.push(10)
st.push(20)
st.push(20)
st.push(30)
st.push(10)
st.push(50)
print('Stack:')
print_stack(st)
print('------')
reversed_stack=conditional_reverse(st)
print('Conditional Reversed Stack:')
print_stack(reversed_stack) # This stack contains 50, 10, 30, 20, 10 in this order whereas top element should be 10
print('------')