# -*- coding: utf-8 -*-
"""111~Lab-5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pVVuy-Ya6RpkKCJgYsX677vAxY2HOMUE
"""

#1
import math
class Circle:
  def __init__(self,radius):
    self.__radius=radius
  def setRadius(self,r):
    self.__radius=r
  def getRadius(self):
    return self.__radius
  def area(self):
    return math.pi*(self.__radius)**2

c1 = Circle(4)
print("First circle radius:" , c1.getRadius())
print("First circle area:" , c1.area())
c2 = Circle(5)
print("Second circle radius:" , c2.getRadius())
print("Second circle area:" , c2.area())

#2
class Triangle:
  def __init__(self,base,height):
    self.__base=base
    self.__height=height
  def getBase(self):
    return self.__base

  def getHeight(self):
    return self.__height

  def setBase(self,b):
    self.__base=b
  def setHeight(self,h):
    self.__height=h
  def area(self):
    return 0.5*self.__base*self.__height

t1 = Triangle(10, 5)
print("First Triangle Base:" , t1.getBase())
print("First Triangle Height:" , t1.getHeight())
print("First Triangle area:" ,t1.area())


t2 = Triangle(5, 3)
print("Second Triangle Base:" , t2.getBase())
print("Second Triangle Height:" , t2.getHeight())
print("Second Triangle area:" ,t2.area())

#3
class Teacher:
  def __init__(self,name,department):
    self.__name=name
    self.__dep=department
    self.__courses=[]
  def addCourse(self,course):
    # self.__c=course
    self.__courses.append(course.c)
  def printDetail(self):
    print('====================================')
    print(f'Name: {self.__name}\nDepartment: {self.__dep}')
    print('List of courses')
    print('====================================')
    for i in self.__courses:
      print(i)
    print('====================================')

class Course:
  def __init__(self,course):
    self.c=course



t1 = Teacher("Saad Abdullah", "CSE")
t2 = Teacher("Mumit Khan", "CSE")
t3 = Teacher("Sadia Kazi", "CSE")
c1 = Course("CSE 110 Programming Language I")
c2 = Course("CSE 111 Programming Language-II")
c3 = Course("CSE 220 Data Structures")
c4 = Course("CSE 221 Algorithms")
c5 = Course("CSE 230 Discrete Mathematics")
c6 = Course("CSE 310 Object Oriented Programming")
c7 = Course("CSE 320 Data Communications")
c8 = Course("CSE 340 Computer Architecture")
t1.addCourse(c1)
t1.addCourse(c2)
t2.addCourse(c3)
t2.addCourse(c4)
t2.addCourse(c5)
t3.addCourse(c6)
t3.addCourse(c7)
t3.addCourse(c8)
t1.printDetail()
t2.printDetail()
t3.printDetail()

#4
class Team:
  def __init__(self,country=None):
    self.__listofplayer=[]
    self.__country=country
  def setName(self,name):
    self.__country=name
  def addPlayer(self,add):
    self.__addplayer=add
    self.__listofplayer.append(add.name)
  def printDetail(self):
    print('=====================')
    print('Team:',self.__country)
    print('List of Players:')
    print(self.__listofplayer)
    print('=====================')


class Player:
  def __init__(self,name):
    self.name=name


b = Team()
b.setName('Bangladesh')
mashrafi = Player("Mashrafi")
b.addPlayer(mashrafi)
tamim = Player("Tamim")
b.addPlayer(tamim)
b.printDetail()
a = Team("Australia")
ponting = Player("Ponting")
a.addPlayer(ponting)
lee = Player("Lee")
a.addPlayer(lee)
a.printDetail()

#5
class Student:
  def __init__(self,name,id,department,email=None,password=None):
    self.name=name
    self.id=id
    self.dep=department
    self.email=email
    self.password=password
    print('Student object is created!')
class Usis:
  def __init__(self):
    print('USIS is ready to use!')
  def login(self,name):
    self.done=''
    self.__name=name
    if self.__name.email==None and self.__name.password==None:
      print('Email and password need to be set.')
    if self.__name.email!=None and self.__name.password!=None:
      print('Login successful!')
      self.done='loged in'
  def advising(self,*n):
    self.courses=''
    if len(n)==1:
     self.name=n[0]
     if self.done!='loged in':
      print('Please login to advise courses!')
     if self.done=='loged in':
      print("You haven't selected any courses.")
    else:
     self.name=n[0]
     for i in n[1:len(n)]:
       self.courses+=i+', '
     if len(n)>4:
       print('You need special approval to take more than 3 courses.')
     else:
       print('Advising successful!')
  def individualDetails(self,n):
    return(f"Name: {n.name}\nID: {n.id}\nDepartment: {n.dep}\nAdvised courses:{self.courses[:-2]}")






rakib = Student("Rakib", 12301455, "CSE")
print("1***********************")
usis_obj = Usis()
print("2***********************")
usis_obj.login(rakib)
print("3***********************")
usis_obj.advising(rakib)
print("4***********************")
rakib.email = "rakib@hotmail.com"
rakib.password = "1234"
print("5***********************")
usis_obj.login(rakib)
print("6***********************")
usis_obj.advising(rakib)
print("7***********************")
usis_obj.advising(rakib, "CSE110", "PHY111", "MAT110", "CSE260")
print("8***********************")
usis_obj.advising(rakib, "CSE110", "PHY111", "MAT110")
print("9***********************")
print(usis_obj.individualDetails(rakib))

#6
class Train :
  def __init__(self,*n):
    self.List=[]
    self.fare=0
    self.count=[]
    self.train=n[0]
    self.start=n[1]
    self.stop=n[-1]
    for i in n[1:]:
      self.List.append(i)
    print(f"Welcome aboard on {self.train}\nStart: {self.start}\nDestination: {self.stop}")
  def addPassenger(self,*b):
     for i in b:
       print(i.name,'welcome aboard')
       self.count.append(i)
  def allPassengerDetails(self):
     for j in self.count:
       if j.From=='' and j.to=='':
          j.From=self.start
          j.to=self.stop
       elif j.From=='':
         j.From=self.start
       elif j.to=='':
         j.to=self.stop
       self.fare='$'+str((self.List.index(j.to)-self.List.index(j.From))*100)
       print(f"Name:{j.name},Start: {j.From},Destination: {j.to},Fair:{self.fare}")
     self.count=[]
class Passenger:
   def __init__(self,*f):
     self.From=''
     self.to=''
     if len(f)==1:
       self.name=f[0]
     if len(f)==2:
       self.name=f[0]
       self.From=f[1]
     if len(f)==3:
       self.name=f[0]
       self.From=f[1]
       self.to=f[2]
t1 = Train('T1-Express','New York','Manhattan','Brooklyn','Boston')
print("1========================")
p1 =Passenger("Naruto")
t1.addPassenger(p1)
p2 = Passenger("Sasuke","Manhattan")
p3 = Passenger("Hinata","Manhattan","Brooklyn")
print("2========================")
t1.addPassenger(p2,p3)
print("3========================")
t1.allPassengerDetails()
print("4========================")
t2 = Train('Europe-Express','London','Paris','Brussels','Turkey')
print("5========================")
p4 =Passenger("Max","London","Brussels")
p5 = Passenger("Eleven","Paris")
p6 = Passenger("Mike","Brussels")
t2.addPassenger(p4,p5,p6)
print("6========================")
t2.allPassengerDetails()

#7
class  BracuStudent:
  def __init__(self,name,adress):
    self.name=name
    self.home=adress
    self.Pass=""
  def show_details(self):
    print(f"Student Name: {self.name}\nLives in {self.home}")
    if self.Pass=="":
      self.Pass=False
      print(f"Have Bus Pass? {self.Pass}")
    else:
      self.Pass=True
      print(f"Have Bus Pass? {self.Pass}")
  def get_pass(self):
    self.Pass=True

class BracuBus:
  def __init__(self,location,capacity=2):
    self.location=location
    self.capacity=capacity
    self.passenger=[]
    self.passenger_count=0
  def show_details(self):
    print(f"Bus Route: {self.location}\nPassengers Count: {self.passenger_count} (Max: {self.capacity})\nPassengers On Board: {self.passenger}")

  def board(self,*passenger):
    if len(passenger)==0:
      print("No passenger!")
    else:
      for i in passenger:
        name=i.name
        home=i.home
        Pass=i.Pass
        if Pass==False:
          print("You don't have bus pass!")
        elif home!=self.location:
          print("You got on wrong bus!")
        else:
          if len(self.passenger)<=self.capacity-1:
            self.passenger.append(name)
            self.passenger_count+=1
            print(f"{name} boarded the bus.")
          else:
            print("Bus is full!")
st1 = BracuStudent("Afif", "Mirpur")
print("1===========================")
st2 = BracuStudent("Shanto", "Motijheel")
st3 = BracuStudent("Taskin", "Mirpur")
st1.show_details()
st2.show_details()
print("2===========================")
st3.show_details()
print("3===========================")
bus1 = BracuBus("Mirpur")
bus2 = BracuBus("Azimpur", 5)
bus1.show_details()
bus2.show_details()
print("4===========================")
st2.get_pass()
st3.get_pass()
print("5===========================")
st2.show_details()
st3.show_details()
print("6===========================")
bus1.board()
print("7===========================")
bus1.board(st1, st2)
print("8===========================")
st1.get_pass()
st2.home = "Mirpur"
st1.show_details()
st2.show_details()
print("9===========================")
bus1.board(st1, st2, st3)
print("10===========================")
bus1.show_details()

#8
class Library:
  def __init__(self,library,dict1):
    self.library=library
    self.book_availability=dict1
    self.borrower_details={}
  def details(self):
    print(f"{self.library} Library details\nBorrower details:\n{self.borrower_details}\nBooks availability:\n{self.book_availability}")

class Reader:
  def __init__(self,name):
    self.name=name
    self.reader_info={}
    self.book_count=0
  def borrow(self,location,*books):
    book_availability=location.book_availability
    borrower_details=location.borrower_details
    count=0
    for i in books:
      if self.book_count<5:
        for key,value in book_availability.items():
          if i==key and value!=0:
            self.book_count+=1
            book_availability[key]=value-1
            print(f"{i} book is borrowed successfully.")
          elif i==key and value==0:
            print(f"{key} books are not available at the moment.")
        if i not in self.reader_info and book_availability[i]!=0:
          count+=1
          self.reader_info[i]=count
          count=0
        elif i in self.reader_info:
          value=self.reader_info[i]
          self.reader_info[i]=value+1
      else:
        print("You cannot borrow more than 5 books.")
    borrower_details[self.name]=self.book_count

  def readerInfo(self,book=None):
    if book==None:
      print(f"{self.name}, you have {self.book_count} book(s) with you.")
      for key,value in self.reader_info.items():
        print(f"Books on {key}: {value}")
    else:
        for key,value in self.reader_info.items():
          if book==key:
            print(f"{self.name}, you have {value} {key} book(s) with you.")
L1=Library('Dhaka',{'Arts':15,'Fiction':135,'Politics':2,'Science':11,'Poetry':15})
L1.details()
print("1----------------------")
r1=Reader('Aladdin')
r1.borrow(L1,'Arts','Fiction','Fiction','Politics')
print("2----------------------")
r1.borrow(L1,'Politics','Fiction')
print("3----------------------")
r1.readerInfo()
print("4----------------------")
r1.readerInfo('Fiction')
print("5----------------------")
L1.details()
print("6----------------------")
r2=Reader('Jasmine')
r2.borrow(L1,'Politics','Poetry')
print("7----------------------")
r2.readerInfo()
print("8----------------------")
L1.details()