# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hMkwDjNLHuHTnlDmESaGxixWW7qfwovi
"""

#6
class Train :
  def __init__(self,*n):
    self.List=[]
    self.fare=0
    self.count=[]
    self.train=n[0]
    self.start=n[1]
    self.stop=n[-1]
    for i in n[1:]:
      self.List.append(i)
    print(f"Welcome aboard on {self.train}\nStart: {self.start}\nDestination: {self.stop}")
  def addPassenger(self,*b):
     for i in b:
       print(i.name,'welcome aboard')
       self.count.append(i)
  def allPassengerDetails(self):
     for j in self.count:
       self.fare=(self.List.index(j.to)-self.List.index(j.From))*100
       print(f"Name:{j.name},Start: {j.From},Destination: {j.to},Fair:{self.fare}")
     self.count=[]
class Passenger:
   def __init__(self,*f):
     q=Train()
     if len(f)==1:
       self.name=f[0]
       self.From=q.start
       self.to=q.stop
     if len(f)==2:
       self.name=f[0]
       self.From=f[1]
       self.to=q.stop
     if len(f)==3:
       self.name=f[0]
       self.From=f[1]
       self.to=f[2]




t1 = Train('T1-Express','New York','Manhattan','Brooklyn','Boston')
print("1========================")
p1 =Passenger("Naruto")
t1.addPassenger(p1)
p2 = Passenger("Sasuke","Manhattan")
p3 = Passenger("Hinata","Manhattan","Brooklyn")
print("2========================")
t1.addPassenger(p2,p3)
print("3========================")
t1.allPassengerDetails()
print("4========================")
t2 = Train('Europe-Express','London','Paris','Brussels','Turkey')
print("5========================")
p4 =Passenger("Max","London","Brussels")
p5 = Passenger("Eleven","Paris")
p6 = Passenger("Mike","Brussels")
t2.addPassenger(p4,p5,p6)
print("6========================")
t2.allPassengerDetails()