# -*- coding: utf-8 -*-
"""111~2  (22201379)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ALqHULftdceF43-ijdSb6YqgZIa7famv
"""

#1
def myfunction(n1,n2):
  if n1!=0 and n2!=0:
   t=(n1/n2)-(n1//n2)
  else:
    t=0
  return t
print(myfunction(5,2))

#2
def dietplan(h,w):
  bmi=w/(h/100)**2
  ro_num=round(bmi,1)
  if bmi<18.5:
    print('Score is',str(ro_num)+'.',"You are Underweight")
  elif 18.5<=bmi<=24.9:
    print('Score is',str(ro_num)+'.',"You are Normal")
  elif 25<=bmi<=30:
    print('Score is',str(ro_num)+'.',"You are Overweight")
  elif bmi>30:
    print('Score is',str(ro_num)+'.',"You are Obese")
dietplan(175,96)

#3
def myfunc(min,max,div):
  sum=0
  for i in range(min,max):
    if i%div==0:
      sum+=i
  return sum
print(myfunc(3,16,3))

#4
def myorder(burger,place='Mohakhali'):
   burger1={'BBQ Chicken Cheese Burger':250,'Beef Burger':170,'Naga Drums':200}
   total=0
   total1=0
   for i,j in burger1.items():
     if i==burger:
       total+=j
     else:
       continue
   if place=='Mohakhali':
     total1+=40
   else:
     total1+=60
   total2=((8*total)/100)+total+total1
   return total2
burger=input()
place=input()
if place!='':
  print(myorder(burger,place))
else:
  print(myorder(burger))

# Task 05
def replace_domain(email, new, old="kaaj.com"):
 count=0
 for i in range(len(email)):
  if email[i]=="@":
   count=i
   break
 if email[count+1: ]==old:
    new_email=email[:count+1]+new
    return "Changed: "+new_email
 else:
    return "Unchanged: "+email
print(replace_domain('bob@sheba.xyz','sheba.xyz'))

#6
def name (n):
     vowel=['a','e','i','o','u','A','E','I','O','U']
     total=0
     vowel1=''
     for i in n:
       if i in vowel:
         vowel1+=i+', '
         total+=1
     if total==0:
       print('No vowels in the name')
     else:
       print('vowels:'+vowel1[:-2],'Total number of vowels:',total)
name(input())

#7
def myfunc(n):
  add=''
  reverce=''
  for j in n:
     if j==' ':
       continue
     else:
       add+=j
  for i in range(len(add)-1,-1,-1):
    reverce+=add[i]
  if add==reverce:
    print('Palindrome')
  else:
    print('Not a Palindrome')
myfunc('madam')

#8
def function_name(n):
  year=n//365
  mont=n%365//30
  day=(n%365)%30
  print(year,'years,',mont,'months and',day,'days')
function_name(int(input()))

#9
def myfunc(n):
  a=[]
  s1=''
  s2=''
  for i in n:
    if(i=='.')or(i='?')or(i=='!'):
      s1+=i
      s1=s1.strip(" ")
      a.append(s1)
      s1=''
    else:
      s1+=i
  for j in a:
    for k in range(len(j)):
      if(k==0):
        s2+=chr(ord(j[k]-32))
      elif ((j[k]=='i')and (j[k-1]==' ')and(j[k]==' ')):
        s2+=chr(ord(j[k])-32)
      elif (k==(len(j)-1)):
        s2+=j[k]+' '
      else:
        s2+=j[k]
  print(s2)
myfunc("my favourite animal is a dog. a dog has sharp-teeth so that it can eat flesh very easily. do you know my pet dog's name? i love my pet very much.")