# -*- coding: utf-8 -*-
"""221-Lab--1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q_q4TevFGzz3GNIOTFo0RvhUXc5bwKFc
"""

#1A

inpt = open('input1a.txt','r')
temp=inpt.readline()
T=int(temp)
outpt=open('output1a.txt','w')
for i in range(T):
  N=int(inpt.readline())
  if i==T-1:
    if N%2!=0:
      outpt.write(f'{N} is an Odd number.')
    else:
      outpt.write(f'{N} is an Even number.')
  else:
    if N%2!=0:
      outpt.write(f'{N} is an Odd number.\n')
    else:
      outpt.write(f'{N} is an Even number.\n')

#1B
inpt = open('input1b.txt','r')
temp=inpt.readline()
T=int(temp)
outpt=open('output1b.txt','w')
for i in range(T):
   N=(inpt.readline())
   number1=int(N.split(' ')[1])
   operator= (N.split(' ')[2])
   number2=int(N.split(' ')[3])
   if i==T-1:
    if operator=="+":
     outpt.write(f"The result of {number1} {operator} {number2} is {number1+number2}")
    elif operator=="-":
     outpt.write(f"The result of {number1} {operator} {number2} is {number1-number2}")
    elif operator=="*":
     outpt.write(f"The result of {number1} {operator} {number2} is {number1*number2}")
    elif operator=="/":
     outpt.write(f"The result of {number1} {operator} {number2} is {number1/number2}")
   else:
    if operator=="+":
     outpt.write(f"The result of {number1} {operator} {number2} is {number1+number2}\n")
    elif operator=="-":
     outpt.write(f"The result of {number1} {operator} {number2} is {number1-number2}\n")
    elif operator=="*":
     outpt.write(f"The result of {number1} {operator} {number2} is {number1*number2}\n")
    elif operator=="/":
     outpt.write(f"The result of {number1} {operator} {number2} is {number1/number2}\n")