# -*- coding: utf-8 -*-
"""111~LAB-8(22201379)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YA8XNKwKurTJZZhQjtqNrYpMQMGDbFgp
"""

#1

class RealNumber:

    def __init__(self, r=0):
        self.__realValue = r
    def getRealValue(self):
        return self.__realValue
    def setRealValue(self, r):
        self.__realValue = r
    def __str__(self):
        return 'RealPart: '+str(self.getRealValue())

class ComplexNumber(RealNumber):
  def __init__(self,r=1,i=1):
    super().__init__(r/1)
    self.imaginary=i
  def __str__(self):
    return (f'RealPart: {self.getRealValue()}\nImaginaryPart: {self.imaginary/1}')

cn1 = ComplexNumber()
print(cn1)
print('---------')
cn2 = ComplexNumber(5,7)
print(cn2)

#2
class RealNumber:
    def __init__(self, number=0):
        self.number = number
    def __add__(self, anotherRealNumber):
        return self.number + anotherRealNumber.number
    def __sub__(self, anotherRealNumber):
        return self.number - anotherRealNumber.number
    def __str__(self):
        return str(self.number)
class ComplexNumber(RealNumber):
  def __init__(self,num1,num2):
    if type(num1)==int:
      super().__init__(num1)
      self.i=num2
    else:
      super().__init__(num1.number)
      self.i=num2
  def __str__(self):
    return f"{self.number} + {self.i}i"
  def __add__(self,self1):
    return f"{self.number+self1.number} + {self.i+self1.i}i"
  def __sub__(self, self1):
    if (self.i-self1.i)<0:
      return f"{self.number-self1.number} {self.i-self1.i}i"
    else:
      return f"{self.number-self1.number} + {self.i-self1.i}i"

r1 = RealNumber(3)
r2 = RealNumber(5)
print(r1+r2)
cn1 = ComplexNumber(2, 1)
print(cn1)
cn2 = ComplexNumber(r1, 5)
print(cn2)
cn3 = cn1 + cn2
print(cn3)
cn4 = cn1 - cn2
print(cn4)

#3
class Account:
    def __init__(self, balance):
        self._balance = balance

    def getBalance(self):
        return self._balance

class CheckingAccount(Account):
  numberOfAccount=0
  def __init__(self,balance=0.00):
    super().__init__(balance)
    CheckingAccount.numberOfAccount+=1
  def __str__(self):
    a="{:.2f}".format(self.getBalance())
    return (f"Account Balance:{a} ")
print('Number of Checking Accounts: ', CheckingAccount.numberOfAccount)
print(CheckingAccount())
print(CheckingAccount(100.00))
print(CheckingAccount(200.00))
print('Number of Checking Accounts: ', CheckingAccount.numberOfAccount)

#4
class Fruit:
    def __init__(self, formalin=False, name=''):
        self.__formalin = formalin
        self.name = name

    def getName(self):
        return self.name

    def hasFormalin(self):
        return self.__formalin

class testFruit:
    def test(self, f):
        print('----Printing Detail-----')
        if f.hasFormalin():
            print('Do not eat the',f.getName(),'.')
            print(f)
        else:
            print('Eat the',f.getName(),'.')
            print(f)
class Mango(Fruit,testFruit):
        def __init__(self,formalin=True,name='Mango'):
           super().__init__(formalin,name)
        def __str__(self):
          return 'Mangos are bad for you'
class Jackfruit(Fruit,testFruit):
        def __init__(self,formalin=False,name='Jackfruit'):
            super().__init__(formalin,name)
        def __str__(self):
          return 'Jackfruits are good for you'
m = Mango()
j = Jackfruit()
t1 = testFruit()
t1.test(m)
t1.test(j)

# Task-5
class Exam:
    def __init__(self,marks):
        self.marks = marks
        self.time = 60

    def examSyllabus(self):
        return "Maths , English"
    def examParts(self):
        return "Part 1 - Maths\nPart 2 - English\n"

class ScienceExam(Exam):
  def __init__(self,marks,time,*sub):
    super().__init__(marks)
    self.time=time
    self.sub=sub

  def examSyllabus(self):
    basic_sub=super().examSyllabus()+" , "
    for i in self.sub:
      basic_sub+=i+" , "
    return basic_sub[:-2]

  def examParts(self):
    num=0
    for i in self.sub:
      num+=1
    list1=[]
    for i in range(1,num+1):
      list1.append(i)
    str1=""
    for i in range(len(list1)):
      str1+= f"Part {i+3} - {self.sub[i]}\n"
    return(super().examParts()+str1[:-2])

  def __str__(self):
    return f"Marks: {self.marks} Time: {self.time} minutes Number of Parts: {len(self.sub)+2}"


engineering = ScienceExam(100,90,"Physics","HigherMaths")
print(engineering)
print('----------------------------------')
print(engineering.examSyllabus())
print(engineering.examParts())
print('==================================')
architecture = ScienceExam(100,120,"Physics","HigherMaths","Drawing")
print(architecture)
print('----------------------------------')
print(architecture.examSyllabus())
print(architecture.examParts())

#6
class Shape3D:

  pi = 3.14159
  def __init__(self, name = 'Default', radius = 0):
    self._area = 0
    self._name = name
    self._height = 'No need'
    self._radius = radius

  def calc_surface_area(self):
    return 2 * Shape3D.pi * self._radius

  def __str__(self):
      return "Radius: "+str(self._radius)

class Sphere(Shape3D):
  def __init__(self,name,radius):
    super().__init__(name,radius)
    print(f"Shape name: {self._name}, Area Formula: 4 * pi * r * r")
  # def calc_surface_area(self):
  #   self.a=self.calc_surface_area()
  def __str__(self):
    return (f"Radius: {self._radius}, Height: {self._height}\nArea: {self.calc_surface_area()*2*self._radius}")

class Cylinder(Shape3D):
  def __init__(self,name,radius,height):
    super().__init__(name,radius)
    self.h=height
    print(f"Shape name: {self._name}, Area Formula: 2 * pi * r * (r + h)")
  # def calc_surface_area(self):
  #   self.a=self.calc_surface_area()
  def __str__(self):
    return (f"Radius: {self._radius}, Height: {self.h}\nArea: {self.calc_surface_area()*(self._radius+self.h)}")


sph = Sphere('Sphere', 5)
print('----------------------------------')
sph.calc_surface_area()
print(sph)
print('==================================')
cyl = Cylinder('Cylinder', 5, 10)
print('----------------------------------')
cyl.calc_surface_area()
print(cyl)

#7
class PokemonBasic:

  def __init__(self, name = 'Default', hp = 0, weakness = 'None', type = 'Unknown'):
    self.name = name
    self.hit_point = hp
    self.weakness = weakness
    self.type = type

  def get_type(self):
    return 'Main type: ' + self.type

  def get_move(self):
    return 'Basic move: ' + 'Quick Attack'

  def __str__(self):
    return "Name: " + self.name + ", HP: " + str(self.hit_point) + ", Weakness: " + self.weakness
class PokemonExtra(PokemonBasic):
  def __init__(self,name,hp,weakness,type1,type2=None,others=None):
    super().__init__(name,hp,weakness,type1)
    self.ov=others
    self.t2=type2
  def get_type(self):
    if self.ov and self.t2!=None:
      return 'Main type: ' + self.type +','+' Secondary type: ' + self.t2
    else:
       return super().get_type()
  def get_move(self):
    a=''
    if self.ov and self.t2!=None:
      for i in self.ov:
        a+=i+', '
      return (f"Basic move: Quick Attack\nOther move: {a[:len(a)-2]}")
    else:
      return super().get_move()
print('\n------------Basic Info:--------------')
pk = PokemonBasic()
print(pk)
print(pk.get_type())
print(pk.get_move())

print('\n------------Pokemon 1 Info:-------------')
charmander = PokemonExtra('Charmander', 39, 'Water', 'Fire')
print(charmander)
print(charmander.get_type())
print(charmander.get_move())

print('\n------------Pokemon 2 Info:-------------')
charizard = PokemonExtra('Charizard', 78, 'Water', 'Fire', 'Flying', ('Fire Spin', 'Fire Blaze'))
print(charizard)
print(charizard.get_type())
print(charizard.get_move())

#8
class Team:
    def __init__(self, name):
        self.name = "default"
        self.total_player = 5
    def info(self):
        print("We love sports")
class FootBallTeam(Team):
      def __init__(self,name):
        self.name=name
        self.total_player=11
      def info(self):
        print(f"Our name is {self.name}\nWe play Football")
        super().info()
class CricketTeam(Team):
      def __init__(self,name):
        self.name=name
        self.total_player=11
      def info(self):
        print(f"Our name is {self.name}\nWe play Cricket")
        super().info()
class Team_test:
    def check(self, tm):
        print("=========================")
        print("Total Player: ", tm.total_player)
        tm.info()
f = FootBallTeam("Brazil")
c = CricketTeam("Bangladesh")
test = Team_test()
test.check(f)
test.check(c)

# Task-9
class Pokemon:

    def __init__(self, p):
        self.pokemon = p
        self.pokemon_type = "Needs to be set"
        self.pokemon_weakness = "Needs to be set"
    def kind(self):
        return self.pokemon_type
    def weakness(self):
        return self.pokemon_weakness
    def what_am_i(self):
        print("I am a Pokemon.")

class Pikachu(Pokemon):
  def __init__(self,name="Pikachuy"):
    super().__init__(name)
    self.pokemon_type = "Electric"
    self.pokemon_weakness = "Ground"
  def what_am_i(self):
    print("I am a Pokemon.")
    print("I am Pikachu")

class Charmander(Pokemon):
  def __init__(self,name="Charmander"):
    super().__init__(name)
    self.pokemon_type = " Fire"
    self.pokemon_weakness = "Water, Ground and Rock"
  def what_am_i(self):
    print("I am a Pokemon.")
    print("I am Charmander")
pk1 = Pikachu()
print("Pokemon:", pk1.pokemon)
print("Type:", pk1.kind())
print("Weakness:", pk1.weakness())
pk1.what_am_i()
print("========================")
c1 = Charmander()
print("Pokemon:", c1.pokemon)
print("Type:", c1.kind())
print("Weakness:", c1.weakness())
c1.what_am_i()

# Task-10
class Department:
    def __init__(self, s):
        self.semester = s
        self.name = "Default"
        self.id = -1

    def student_info(self):
        print("Name:", self.name)
        print("ID:", self.id)

    def courses(self, c1, c2, c3):
        print("No courses Approved yet!")


class CSE(Department):
    def __init__(self,name,id,semester):
      super().__init__(semester)
      self.name=name
      self.id=id

    def courses(self,*courses):
      print(f"Courses Approved to this CSE student in {self.semester} semester :")
      for i in courses:
        print(i)

class EEE(Department):
    def __init__(self,name,id,semester):
      super().__init__(semester)
      self.name=name
      self.id=id

    def courses(self,*courses):
      print(f"Courses Approved to this EEE student in {self.semester} semester :")
      for i in courses:
        print(i)

s1 = CSE("Rahim", 16101328,"Spring2016")
s1.student_info()
s1.courses("CSE110", "MAT110", "ENG101")
print("==================")
s2 = EEE("Tanzim", 18101326, "Spring2018")
s2.student_info()
s2.courses("Mat110", "PHY111", "ENG101")
print("==================")
s3 = CSE("Rudana", 18101326, "Fall2017")
s3.student_info()
s3.courses("CSE111", "PHY101", "MAT120")
print("==================")
s4 = EEE("Zainab", 19201623, "Summer2019")
s4.student_info()
s4.courses("EEE201", "PHY112", "MAT120")

#Fall2022 (setA)
#1
class Netflix:
  count=0
  shows=[]
  def __init__(self,show,genre,ep=10):

    self.show=show
    self.g=genre
    self.ep=ep
    self.g1=''
    Netflix.count+=1
    Netflix.shows.append(self.show)
    for i in self.g:
      self.g1+=i+', '
  def __str__(self):

    return (f"Show name: {self.show}\nEpisodes: {self.ep}\nGenre: {self.g1[:len(self.g1)-2]}")
  @classmethod
  def printDetails(cls):
    print(f"Total number of shows: {Netflix.count}")
    for i in Netflix.shows:
      print(i)


s1 = Netflix("Wednesday",["Mystery","Supernatural"],15)
print("==========1==========")
print(s1)
s2 = Netflix("Dark",["Mind-Bending","Sci-fi"])
print("==========2==========")
print(s2)
print("==========3==========")
Netflix.printDetails()
s3 = Netflix("Suits",["Comedy","Courtroom"],20)
print("==========4==========")
print(s3)
s4 = Netflix("Demon Slayer",["Anime"],22)
print("==========5==========")
print(s4)
print("==========6==========")
Netflix.printDetails()

#2
class Mobile:
   countryCodes = {"880": "Bangladesh", "966": "India","455": "USA"}
   def __init__(self, model, simCardStatus):
       self.model = model
       self.__simCardStatus = simCardStatus
       print(f"Model {model} is manufactured.")
   def setSimCardStatus(self,status):
       self.__simCardStatus = status
       print("SIM card status updated successfully.")
   def getSimCardStatus(self):
       return self.__simCardStatus
   def __str__(self):
       return f"Mobile Phone Detail:\nModel: {self.model}\nSIM Card Status: {self.__simCardStatus}"

class Nokia(Mobile):
  def __init__(self,model,sim,balance=0):
    super().__init__(model,sim)
    self.balance=balance
    self.dialCallHistory=[]
  def __str__(self):
    return (f"Mobile Phone Detail:\nModel: {self.model}\nSIM Card Status: {super().getSimCardStatus()}\nBalance: {self.balance} TK")
  def dialCall(self,num):

    if super().getSimCardStatus()==False:
      return 'No SIM card available!'
    else:
      if self.balance==0:
        return("Insufficient balance!")
      else:
        if num[0:3] in Mobile.countryCodes:
         self.dialCallHistory.append(num)
         for i,j in Mobile.countryCodes.items():
           if i==num[0:3] :
              return (f"Dialing the number {num} to {j} region.")
        else:
          return 'Dialing is not allowed in this region.'
  def changeSIMCardStatus(self,s=True):
    super().setSimCardStatus(s)
  def rechargeSIMCard(self,tk):
    self.balance+=tk
    print(f"Recharge successful! Current balance {self.balance} TK.")




N3110 = Nokia("N3110", False)
print("#######################################")
print(N3110)
print("1======================================")
N1100 = Nokia("N1100", True,100)
print("#######################################")
print(N1100)
print("2======================================")
print(N3110.dialCall("88017196xxxx"))
print("3======================================")
N3110.changeSIMCardStatus()
print("4======================================")
print(N3110.dialCall("88017196xxxx"))
print("5======================================")
N3110.rechargeSIMCard(200)
print("6======================================")
print(N3110.dialCall("88017196xxxx"))
print("7======================================")
print(N1100.dialCall("45617196xxxx"))
print("8======================================")
print(N1100.dialCall("45517196xxxx"))
print(N1100.dialCall("96617196xxxx"))
print("9======================================")
print(f"Dial call history for {N1100.model}:{N1100.dialCallHistory}")
print(f"Dial call history for {N3110.model}:{N3110.dialCallHistory}")

class A:
   temp = 7
   def __init__(self):
     self.y = A.temp - 3
     self.sum = self.temp + 2
     A.temp += 3
   def methodA(self, m, n, x=0):
     self.y = self.y + m + (A.temp)
     x = x + 2 + n
     self.sum = self.sum + x + self.temp
     print(x, self.y, self.sum)
class B(A):
   temp = 1
   def __init__(self, obj=None):
      super().__init__()
      self.temp = self.temp + B.temp
      self.sum = 3 + B.temp + A.temp
      if obj != None:
         obj.methodB(3, 6)
      else:
         self.methodB(1, 4)
   def methodB(self, m, n):
      y = self.temp + self.y + n
      B.temp = m + self.y + n
      self.methodA(n, m)
      self.sum = self.y + y + A.temp
      print(self.temp , y, self.sum)
b1 = B()
b2 = B(b1)

#Summer 2022 set-B
#1
class Monster:
  monsterCount=0
  def __init__(self,name,power):
    Monster.monsterCount+=1
    self.name=name
    self.power=power
    self.live=True
  def get_details(self):
    return(f"Name: {self.name}\nPower: {self.power}\nAlive: {self.live}")
  def attack(self,*n):
    if len(n)==0:
      print('No monsters to attack')
    if len(n)==1:
      if self.live and n[0].live==True:
       if self.power>n[0].power:
         n[0].live=False
         Monster.monsterCount-=1
         print(f"Attack successful.{self.name} defeated {n[0].name}")
       else:
         self.live=False
         Monster.monsterCount-=1
         print(f"Attack unsuccessful.{self.name} was defeated by {n[0].name}")
      elif self.live!=True:
       print(self.name,'is not alive to attack')
      elif n[0].live!=True:
       print(f"Cannot attack {n[0].name}. It's not alive.")
    if len(n)==2:
      if self.live==True and n[0].live==True:
        if self.power>n[0].power:
         n[0].live=False
         Monster.monsterCount-=1
         print(f"Attack successful.{self.name} defeated {n[0].name}")
        else:
         self.live=False
         Monster.monsterCount-=1
         print(f"Attack unsuccessful.{self.name} was defeated by {n[0].name}")
      elif self.live!=True:
       print(self.name,'is not alive to attack')
      elif n[0].live!=True:
       print(f"Cannot attack {n[0].name}. It's not alive.")
      if self.live==True and n[1].live==True:
       if self.power>n[1].power:
         n[1].live=False
         Monster.monsterCount-=1
         print(f"Attack successful.{self.name} defeated {n[1].name}")
       else:
         self.live=False
         Monster.monsterCount-=1
         print(f"Attack unsuccessful.{self.name} was defeated by {n[1].name}")
      elif self.live!=True:
       print(self.name,'is not alive to attack')
      elif n[1].live!=True:
       print(f"Cannot attack {n[1].name}. It's not alive.")
monster1 = Monster('Godzilla', 40)
monster2 = Monster('Hydra', 30)
monster3 = Monster('KingKong', 50)
print(f"Number of monsters alive:{Monster.monsterCount}")
print('1--------------------------------')
print(monster1.get_details())
print('2--------------------------------')
print(monster2.get_details())
print('3--------------------------------')
print(monster3.get_details())
print('4--------------------------------')
monster1.attack()
print('5--------------------------------')
monster1.attack(monster2)
print('6--------------------------------')
monster1.attack(monster2, monster3)
print('7--------------------------------')
print(f"Number of monsters alive:{Monster.monsterCount}")
print('8--------------------------------')
print(monster2.get_details())
print('9--------------------------------')
monster2.attack(monster1)

#2

class User:
   activities = ["Post", "Like", "Comment"]
   def __init__(self, name,email):
     self.name = name
     self.email = email
   def UserActivity(self, activityType):
      if activityType in User.activities:
            return True
      else:
           return False
   def userDetail(self):
         return f"User Detail:\nName:{self.name}\nEmail: {self.email}"
class BracbookUser(User):
  def __init__(self,name,email,num='Not set'):
    super().__init__(name,email)
    self.phn=num
    self.activity=''
  def userDetail(self):
    if self.activity=='':
     return(f"{super().userDetail()}\nPhone: {self.phn}\nActivity log: No recent activity.")
    else:
      return(f"{super().userDetail()}\nPhone: {self.phn}\nActivity log: {self.activity[:len(self.activity)-1]}")

  def UserActivity(self,activity):
    if super().UserActivity(activity)==True:
      print(f"{self.name} has {activity}(d/ed) successfully.")
      self.activity+=activity+','
    else:
      print(f"No activities found like {activity}")



user1 = BracbookUser("Rakait","xyz@gmail.com")
print("1===========================")
print(user1.userDetail())
print("2===========================")
user2 = BracbookUser("Sazzad","abc@gmail.com",
"01727xxxxxx")
print("3===========================")
print(user2.userDetail())
print("4===========================")
user1.UserActivity("Like")
print("5===========================")
user1.UserActivity("Comment")
print("6===========================")
print(user1.userDetail())
print("7===========================")
user2.UserActivity("Share")
print("8===========================")
user2.UserActivity("Comment")
print("9===========================")
print(user2.userDetail())

class A:
   temp = 5
   def __init__(self):
      self.y = A.temp - 2
      self.sum = A.temp + 1
      A.temp += 3
   def methodA(self, m, n):
      x = 0
      self.y = self.y + m + (A.temp)
      x = x + 2 + n
      print(x, self.y, self.sum)
      self.methodB(-2, 6)
      self.sum = self.sum + x + A.temp
      self.methodB(-4, self.sum, 3)
   def methodB(self, m, n):
      y = 5
      y = y + self.y
      self.sum = B.x + y + n
      print(B.x, y, self.sum)
class B(A):
   x = 1
   def __init__(self, obj=None):
      super().__init__()
      if obj != None:
        obj.sum = 11
      self.y = A.temp + 4
      self.sum = 3 + A.temp + B.x
   def methodB(self, m, n, y=0):
      y = y + self.y + n
      B.x = m + self.y + n
      self.sum = B.x + y + A.temp
      print(B.x, y, self.sum)
b1 = B()
b2 = B(b1)
b1.methodA(-3, -7)

class A:
  temp = 5
  def __init__(self):
   self.y = A.temp - 2
   self.sum = self.temp + 1
   A.temp += 3
  def methodA(self, m, n, x=0):
     self.y = self.y + m + (A.temp)
     x = x + 4 + n
     self.sum = self.sum + x + self.temp
     print(x, self.y, self.sum)
class B(A):
 temp = 1
 def __init__(self, obj=None):
   super().__init__()
   self.temp = self.temp + B.temp
   self.sum = 5 + B.temp + A.temp
   if obj != None:
     obj.methodB(6, 3)
   else:
    self.methodB(4, 1)
 def methodB(self, m, n):
    y = self.temp + self.y + n
    B.temp = m + self.y + n
    self.methodA(n, m)
    self.sum = self.y + y + A.temp
    print(self.temp , y, self.sum)
b1 = B()
b2 = B(b1)