# -*- coding: utf-8 -*-
"""Recursion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pofewXidnSEJ5YXcK4M2WrlaLzhWkyhL
"""

# You must run this cell to install dependency
! pip3 install fhm-unittest
! pip3 install fuzzywuzzy
import fhm_unittest as unittest
import numpy as np
import math

#Run this cell
class Node:
  def __init__(self, elem, next = None):
    self.elem = elem
    self.next = next

def create_linked_list(arr):
  head = Node(arr[0])
  tail = head
  for i in arr[1:]:
    new_node = Node(i)
    tail.next = new_node
    tail = new_node
  return head

"""# **01**
Given a non-negative int n, return the sum of its digits recursively (no loops). Note that mod (%)
by 10 yields the rightmost digit (126 % 10 is 6), while divide (/) by 10 removes the rightmost digit
(126 / 10 is 12).
"""

def sumDigits(n):
     if n==0:
      return 0
     return (n%10)+sumDigits(n//10)
print(sumDigits(126))
print(sumDigits(49))
print(sumDigits(12))

"""# **02**
We have bunnies standing in a line, numbered 1, 2, ... The odd bunnies (1, 3, ..) have the
normal 2 ears. The even bunnies (2, 4, ..) we'll say have 3 ears, because they each have a
raised foot. Recursively return the number of "ears" in the bunny line 1, 2, ... n (without loops or
multiplication).
"""

def bunnyEars2(n):
    if n == 0:
        return 0
    elif n % 2 == 0:
        return 3 + bunnyEars2(n - 1)
    else:
        return 2 + bunnyEars2(n - 1)

print(bunnyEars2(0)) # Output: 0
print(bunnyEars2(1)) # Output: 2
print(bunnyEars2(2)) # Output: 5

"""# **03**
Given a non-negative int n, return the count of the occurrences of 7 as a digit, so for example
717 yields 2. (no loops). Note that mod (%) by 10 yields the rightmost digit (126 % 10 is 6),
while divide (/) by 10 removes the rightmost digit (126 / 10 is 12).
"""

def count7(n):
    if n == 0:
        return 0
    elif n % 10 == 7:
        return 1 + count7(n // 10)
    else:
        return count7(n // 10)

# Test cases
print(count7(717)) # Output: 2
print(count7(7))   # Output: 1
print(count7(123)) # Output: 0

"""#**4**
Given a string, compute recursively (no loops) the number of lowercase 'x' chars in the string.
"""

def countX(s,i=0):
    if len(s) == 0:
        return 0
    if i<len(s):
      if s[i] == 'x':
        return 1 + countX(s,(i+1))
      else:
        return countX(s,(i+1))
    else:
      return 0

# Test cases
print(countX("xxhixx"))   # Output: 4
print(countX("xhixhix"))  # Output: 3
print(countX("hi"))       # Output: 0
print(countX("hixxxxxxx")) #output:7

"""#**05**
Given a string, compute recursively (no loops) a new string where all appearances of "pi" have
been replaced by "3.14".
"""

def changePi(s):
    if len(s) <= 1:
        return s
    elif s[0:2] == "pi":
        return "3.14" + changePi(s[2:])
    else:
        return s[0] + changePi(s[1:])

# Test cases
print(changePi("xpix"))   # Output: "x3.14x"
print(changePi("pipi"))   # Output: "3.143.14"
print(changePi("pip"))    # Output: "3.14p"

"""#**06**
Given an array of ints, compute recursively the number of times that the value 11 appears in the
array. We'll use the convention of considering only the part of the array that begins at the given
index. In this way, a recursive call can pass index+1 to move down the array. The initial call will
pass in index as 0.
"""

def array11(a, i):
  if len(a)==0:
    return 0
  else:
    if i <len(a):
      if a[i]==11:
        return 1+ array11(a,i+1)
      else:
        return array11(a,i+1)
    else:
      return 0

# Test cases
print(array11([1, 2, 11], 0))  # Output: 1
print(array11([11, 11], 0))    # Output: 2
print(array11([1, 2, 3, 4], 0)) # Output: 0

"""#**07**
Given a string, compute recursively a new string where identical chars that are adjacent in the
original string are separated from each other by a "*".
"""

def pairStar(s):
    if len(s) <= 1:
        return s
    elif s[0] == s[1]:
        return s[0] + "*" + pairStar(s[1:])
    else:
        return s[0] + pairStar(s[1:])
print(pairStar("hello"))
# "hel*lo"
print(pairStar("xxyy"))
#"x*xy*y"
print(pairStar("aaaa"))
#"a*a*a*a"

"""# **08**

Count recursively the total number of "abc" and "aba" substrings that appear in the given string.
"""

def countAbc(s):
    if len(s) <= 2:
        return 0
    elif s[:3] == "abc" or s[:3] == "aba":
        return 1 + countAbc(s[1:])
    else:
        return countAbc(s[1:])
print(countAbc("abc"))
#1
print(countAbc("abcxxabc"))
# 2
print(countAbc("abaxxaba"))
#2

"""# **09**
Given a string, compute recursively the number of times lowercase "hi" appears in the string,
however do not count "hi" that have an 'x' immedately before them
"""

def countHi2(s):
    if len(s) <= 1:
        return 0
    elif s[1:3] == "hi" and s[0] != "x":
      return 1 + countHi2(s[3:])
    else:
        return countHi2(s[1:])
print(countHi2("ahixhi"))
# Output: 1
print(countHi2("ahibhi"))
# Output: 2
print(countHi2("xhixhi"))
# Output: 0

"""# **10**
Given a string and a non-empty substring sub, compute recursively the number of times that
sub appears in the string, without the sub strings overlapping.
"""

def strCount(s, sub):
    if len(s) < len(sub):
        return 0
    elif s[:len(sub)] == sub:
        return 1 + strCount(s[len(sub):], sub)
    else:
        return strCount(s[1:], sub)
print(strCount("catcowcat", "cat"))
# Output: 2
print(strCount("catcowcat", "cow"))
# Output: 1
print(strCount("catcowcat", "dog"))
# Output: 0

"""# **11**
We have a number of bunnies and each bunny has two big floppy ears. We want to compute the
total number of ears across all the bunnies recursively (without loops or multiplication).
"""

def bunnyEars(n):
    if n == 0:
        return 0
    else:
        return 2 + bunnyEars(n - 1)
print(bunnyEars(0)) #0
print(bunnyEars(1)) #2
print(bunnyEars(2)) #4

"""# **12**
We have triangle made of blocks. The topmost row has 1 block, the next row down has 2
blocks, the next row has 3 blocks, and so on. Compute recursively (no loops or multiplication)
the total number of blocks in such a triangle with the given number of rows.
"""

def triangle(rows):
    if rows == 0:
        return 0
    else:
        return rows + triangle(rows - 1)
print(triangle(0)) #0
print(triangle(1)) #1
print(triangle(2)) #3

"""# **13**
Given a string, compute recursively a new string where all the 'x' chars have been removed.
"""

def noX(s):
    if len(s) == 0:
        return s
    elif s[0] == 'x':
        return noX(s[1:])
    else:
        return s[0] + noX(s[1:])
print(noX("xaxb"))
print(noX("abc"))
print( noX("xx"))

"""# **14**
Given an array of ints, compute recursively if the array contains somewhere a value followed in
the array by that value times 10. We'll use the convention of considering only the part of the
array that begins at the given index. In this way, a recursive call can pass index+1 to move
down the array. The initial call will pass in index as 0.
"""

def array220(nums, index):
    if index >= len(nums) - 1:
        return False
    elif nums[index] * 10 == nums[index + 1]:
        return True
    else:
        return array220(nums, index + 1)
print(array220([1, 2, 20], 0))
print(array220([3, 30], 0))
print(array220([3], 0))

"""# **15**
Given a string, compute recursively a new string where all the lowercase 'x' chars have been
moved to the end of the string.
"""

def endX(s):
    if len(s) <= 1:
        return s
    elif s[0] == 'x':
        return endX(s[1:]) + 'x'
    else:
        return s[0] + endX(s[1:])
print(endX("xxre"))
print(endX("xxhixx"))
print(endX("xhixhix"))

"""# **16**
Given a string, compute recursively (no loops) the number of "11" substrings in the string. The
"11" substrings should not overlap.
"""

def count11(s):
    if len(s) <= 1:
        return 0
    elif s[:2] == '11':
        return 1 + count11(s[2:])
    else:
        return count11(s[1:])
print(count11("11abc11"))
# Output: 2
print(count11("abc11x11x11"))
# Output: 3
print(count11("111"))
# Output: 1

"""#  **17**
Given a string that contains a single pair of parenthesis, compute recursively a new string made
of only of the parenthesis and their contents, so "xyz(abc)123" yields "(abc)".
"""

def parenBit(s):
    if s[0] != '(':
        return parenBit(s[1:])
    elif s[-1] != ')':
        return parenBit(s[:-1])
    else:
        return s
print(parenBit("xyz(abc)123"))
print(parenBit("x(hello)"))
print(parenBit("(xy)1"))

"""# **18**
Given a string and a non-empty substring sub, compute recursively if at least n copies of sub
appear in the string somewhere, possibly with overlapping. N will be non-negative.

"""

def strCopies(s, sub, n):
    if len(s) < len(sub):
        return n == 0
    elif s[:len(sub)] == sub:
        return strCopies(s[len(sub):], sub, n - 1)
    else:
        return strCopies(s[1:], sub, n)
print(strCopies("catcowcat", "cat", 2))
#Output: True
print(strCopies("catcowcat", "cow", 2))
#Output: False
print(strCopies("catcowcat", "cow", 1))
#Output: True

"""# **19**
Given a string, compute recursively (no loops) a new string where all the lowercase 'x' chars
have been changed to 'y' chars.
"""

def changeXY(s):
    if len(s) == 0:
        return s
    elif s[0] == 'x':
        return 'y' + changeXY(s[1:])
    else:
        return s[0] + changeXY(s[1:])
print(changeXY("codex"))
# Output: "codey"
print(changeXY("xxhixx"))
# Output: "yyhiyy"
print(changeXY("xhixhix"))
# Output: "yhiyhiy"#

"""# **20**
Given an array of ints, compute recursively if the array contains a 6. We'll use the convention of
considering only the part of the array that begins at the given index. In this way, a recursive call
can pass index+1 to move down the array. The initial call will pass in index as 0.
"""

def array6(nums, index):
    if index >= len(nums):
        return False
    elif nums[index] == 6:
        return True
    else:
        return array6(nums, index + 1)
print(array6([1, 6, 4], 0))
#Output: True
print(array6([1, 4], 0))
#Output: False
print(array6([6], 0))
#Output: True

arr=[3,1,4,2,5]
print(arr[arr[arr[3]]])

"""# **21**
Given a string, compute recursively a new string where all the adjacent chars are now
separated by a "*".
"""

def allStar(s):
    if len(s) <= 1:
        return s
    else:
        return s[0] + '*' + allStar(s[1:])

"""# **22**
We'll say that a "pair" in a string is two instances of a char separated by a char. So "AxA" the A's
make a pair. Pair's can overlap, so "AxAxA" contains 3 pairs -- 2 for A and 1 for x. Recursively
compute the number of pairs in the given string.
"""

def countPairs(s):
    if len(s) <= 2:
        return 0
    elif s[0] == s[2]:
        return 1 + countPairs(s[1:])
    else:
        return countPairs(s[1:])

"""# **23**
Given a string, return recursively a "cleaned" string where adjacent chars that are the same
have been reduced to a single char. So "yyzzza" yields "yza".
"""

def stringClean(s):
    if len(s) <= 1:
        return s
    elif s[0] == s[1]:
        return stringClean(s[1:])
    else:
        return s[0] + stringClean(s[1:])

"""# **24**
Given a string, return true if it is a nesting of zero or more pairs of parenthesis, like "(())" or
"((()))". Suggestion: check the first and last chars, and then recur on what's inside them.
"""

def nestParen(s):
    if len(s) <= 2:
        return s == '()'
    elif s[0] == '(' and s[-1] == ')':
        return nestParen(s[1:-1])
    else:
        return False

"""# **25**
Given a string and a non-empty substring sub, compute recursively the largest substring which
starts and ends with sub and return its length.
"""

def strDist(s, sub):
    if len(s) < len(sub):
        return 0
    elif s[:len(sub)] == sub and s[-len(sub):] == sub:
        return len(s)
    elif s[:len(sub)] != sub:
        return strDist(s[1:], sub)
    else:
        return strDist(s[:-1], sub)

"""# **26**
Given an array of ints, is it possible to choose a group of some of the ints, such that the group
sums to the given target? This is a classic backtracking recursion problem. Once you
understand the recursive backtracking strategy in this problem, you can use the same pattern
for many problems to search a space of choices. Rather than looking at the whole array, our
convention is to consider the part of the array starting at index start and continuing to the end of
the array. The caller can specify the whole array simply by passing start as 0. No loops are
needed -- the recursive calls progress down the array.
"""

def groupSum(start, nums, target):
    if start >= len(nums):
        return target == 0
    elif groupSum(start + 1, nums, target - nums[start]):
        return True
    elif groupSum(start + 1, nums, target):
        return True
    else:
        return False

"""# **27**
Given an array of ints, is it possible to divide the ints into two groups, so that the sums of the
two groups are the same. Every int must be in one group or the other. Write a recursive helper
method that takes whatever arguments you like, and make the initial call to your recursive
helper from splitArray(). (No loops needed.)
"""

def splitArray(nums):
    return splitArrayHelper(nums, 0, 0, 0)

def splitArrayHelper(nums, index, sum1, sum2):
    if index >= len(nums):
        return sum1 == sum2
    elif splitArrayHelper(nums, index + 1, sum1 + nums[index], sum2):
        return True
    elif splitArrayHelper(nums, index + 1, sum1, sum2 + nums[index]):
        return True
    else:
        return False

"""# **28**
Given an array of ints, is it possible to divide the ints into two groups, so that the sum of one
group is a multiple of 10, and the sum of the other group is odd. Every int must be in one group
or the other. Write a recursive helper method that takes whatever arguments you like, and make
the initial call to your recursive helper from splitOdd10(). (No loops needed.)
"""

def splitOdd10(nums):
    return splitOdd10Helper(nums, 0, 0, 0)

def splitOdd10Helper(nums, index, sum1, sum2):
    if index >= len(nums):
        return sum1 % 10 == 0 and sum2 % 2 == 1
    elif splitOdd10Helper(nums, index + 1, sum1 + nums[index], sum2):
        return True
    elif splitOdd10Helper(nums, index + 1, sum1, sum2 + nums[index]):
        return True
    else:
        return False

"""# **29**
Given an array of ints, is it possible to divide the ints into two groups, so that the sum of the two
groups is the same, with these constraints: all the values that are multiple of 5 must be in one
group, and all the values that are a multiple of 3 (and not a multiple of 5) must be in the other.
(No loops needed.)
"""

def split53(nums):
    return split53Helper(nums, 0, 0, 0)

def split53Helper(nums, index, sum5, sum3):
    if index >= len(nums):
        return sum5 == sum3
    elif nums[index] % 5 == 0:
        return

"""# **30**
Given an array of ints, is it possible to choose a group of some of the ints, such that the group
sums to the given target with these additional constraints: all multiples of 5 in the array must be
included in the group. If the value immediately following a multiple of 5 is 1, it must not be
chosen. (No loops needed.)
"""

def groupSum5(start, nums, target):
    if start >= len(nums):
        return target == 0

    # If current number is a multiple of 5
    if nums[start] % 5 == 0:
        # Include the current number, but skip the following 1 if present
        if start < len(nums) - 1 and nums[start + 1] == 1:
            return groupSum5(start + 2, nums, target - nums[start])
        else:
            return groupSum5(start + 1, nums, target - nums[start])

    # Don't include the current number if it's immediately followed by 1
    elif start < len(nums) - 1 and nums[start] != 1 and nums[start + 1] == 1:
        return groupSum5(start + 2, nums, target)

    # Include the current number
    else:
        return groupSum5(start + 1, nums, target - nums[start]) or groupSum5(start + 1, nums, target)


# Test cases
print(groupSum5(0, [2, 5, 10, 4], 19)) # Output: True
print(groupSum5(0, [2, 5, 10, 4], 17)) # Output: True
print(groupSum5(0, [2, 5, 10, 4], 12)) # Output: False