# -*- coding: utf-8 -*-
"""220--1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mI2kDVBGMd_0u87grOR6q7T4NtNTo6xX
"""

# You must run this cell to install dependency
! pip3 install fhm-unittest
! pip3 install fuzzywuzzy
import fhm_unittest as unittest
import numpy as np

#Task 01: Merge Lineup
import numpy as np

def mergeLineup(pokemon_1, pokemon_2):

  result = np.array([0]*len(pokemon_1))
  j=len(pokemon_2)-1
  for i in range(len(pokemon_1)):

        if pokemon_1[i] is not None and pokemon_2[j] is not None:
            result[i] = pokemon_1[i] + pokemon_2[j]
        if pokemon_1[i] is None:
            result[i] = pokemon_2[j]
        elif pokemon_2[j] is None:
            result[i] = pokemon_1[i]
        j-=1

  return result

print("///  Task 01: Merge Lineup  ///")
pokemon_1 = np.array([12, 3, 25, 1, None])
pokemon_2 = np.array([5, -9, 3, None, None] )
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 1: {returned_value}') # This should print [12, 3, 28, -8, 5]
unittest.output_test(returned_value, np.array([12, 3, 28, -8, 5]))

pokemon_1 = np.array([4, 5, -1, None, None])
pokemon_2 = np.array([2, 27, 7, 12, None])
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 1: {returned_value}') # This should print [4,17,6,27,2]
unittest.output_test(returned_value, np.array([4,17,6,27,2]))

# Task 02: Discard Cards
def discardCards(cards, t):
  count=0
  while i<len(cards):




print("///  Task 02: Discard Cards  ///")
cards = np.array([1,3,7,2,5,2,2,2,0])
returned_value = discardCards(cards, 2)
print(f'Task 2: {returned_value}') # This should print [1,3,7,5,2,2,0,0,0]
unittest.output_test(returned_value, np.array([1,3,7,5,2,2,0,0,0]))

cards = np.array([5,5,5,0,0])
returned_value = discardCards(cards, 5)
print(f'Task 2: {returned_value}') # This should print [5,0,0,0,0]
unittest.output_test(returned_value, np.array([5,0,0,0,0]))

# Task 03: DUBER Fare Splitting
def findGroups(money, fare):
  # TO DO
  # Print outputs inside the method

print("///  Task 03: DUBER Fare Splitting  ///")
money = np.array( [120, 100, 150, 50, 30])
fare = 150
print(f'Task 3:')
findGroups(money, fare) # This should print

# Group 1 : 120, 30
# Group 2 : 100, 50
# Group 3 : 150


money = np.array( [60, 150, 60, 30, 120, 30])
fare = 180
print(f'Task 3:')
findGroups(money, fare) # This should print

# Group 1 : 60, 120
# Group 2 : 30, 150
# Ungrouped : 30 60

# Task 04: Get Those Hobbies
def analyzeHobbies(* participants): #(* arguments) is used for variable number of parameters
  # TO DO
  # Print outputs inside the method



print("///  Task 04: Get Those Hobbies  ///")
participant_1 = np.array( ["Hiking", "Reading", "Photography", "Cooking"])
participant_2 = np.array( ["Reading", "Hiking", "Painting"])
participant_3 = np.array( ["Hiking", "Cooking", "Photography"])
print(f'Task 4:')
analyzeHobbies(participant_1, participant_2, participant_3) #This should print

#Unique Activities in the Town:
#['Photography', 'Painting', 'Cooking', 'Reading', 'Hiking']

#Statistics:
#2 participant(s) like(s) Photography.
#1 participant(s) like(s) Painting.
#2 participant(s) like(s) Cooking.
#2 participant(s) like(s) Reading.
#3 participant(s) like(s) Hiking.



participant_1 = np.array( ["Gardening", "Traveling"])
participant_2 = np.array( ["Singing", "Gardening", "Painting"])
print(f'Task 4:')
analyzeHobbies(participant_1, participant_2) #This should print

#Unique Activities in the Town:
#[Gardening, Traveling, Singing, Painting]

import numpy as np


def calculate_mean(a):
 count=0
 sum=0
 mean=0
 for i in range (len(a)):
  count+=1
  sum+=a[i]
 mean=sum/len(a)
 print(mean)
def calculate_div(a):
 sum2=0
 div=0
 for j in range (len(a)):
  sum2+=(a[j]-{calculate_mean.mean})**2
 div=(((sum2)/(len(a)-1))**0.5)
 print(div)

a=np.array([10, 8, 13, 9, 14, 25, -5, 20, 7, 7, 4])
b=calculate_mean(a)
c=calculate_div(a)